@extends('Mindigo-dashboard::layouts')
@section('title', __('teacher-live-session::app.configuration_title'))
@section('content')
<div class="min-h-screen bg-slate-50 p-4 sm:p-6"><div class="mx-auto max-w-6xl space-y-5">
    <header class="flex flex-wrap items-center justify-between gap-4"><div><p class="text-xs font-black uppercase tracking-wider text-green-700">Auronsoft Live</p><h1 class="mt-1 text-2xl font-black text-slate-950">@lang('teacher-live-session::app.configuration_title')</h1><p class="mt-1 text-sm font-semibold text-slate-500">@lang('teacher-live-session::app.configuration_subtitle')</p></div><a href="{{ route('admin.live-providers.health') }}" class="inline-flex h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-black text-slate-700 no-underline"><x-heroicon-o-signal class="h-4 w-4" />@lang('teacher-live-session::app.provider_health_title')</a></header>
    <section class="grid gap-3 sm:grid-cols-2"><article class="rounded-2xl border border-slate-200 bg-white p-4"><div class="flex items-center justify-between"><div><h2 class="font-black text-slate-900">Google Meet OAuth</h2><p class="mt-1 text-xs font-semibold text-slate-500">GOOGLE_MEET_CLIENT_ID / CLIENT_SECRET</p></div><span class="rounded-full px-2.5 py-1 text-xs font-black {{ $credentials['google_meet'] ? 'bg-green-50 text-green-700' : 'bg-amber-50 text-amber-700' }}">{{ $credentials['google_meet'] ? __('teacher-live-session::app.configured') : __('teacher-live-session::app.not_configured') }}</span></div></article><article class="rounded-2xl border border-slate-200 bg-white p-4"><div class="flex items-center justify-between"><div><h2 class="font-black text-slate-900">Zoom OAuth</h2><p class="mt-1 text-xs font-semibold text-slate-500">ZOOM_CLIENT_ID / CLIENT_SECRET</p></div><span class="rounded-full px-2.5 py-1 text-xs font-black {{ $credentials['zoom'] ? 'bg-green-50 text-green-700' : 'bg-amber-50 text-amber-700' }}">{{ $credentials['zoom'] ? __('teacher-live-session::app.configured') : __('teacher-live-session::app.not_configured') }}</span></div></article></section>
    <form method="POST" action="{{ route('admin.live-providers.configuration.update') }}" class="space-y-5">@csrf @method('PUT')
        <section class="rounded-2xl border border-slate-200 bg-white p-5"><h2 class="font-black text-slate-900">@lang('teacher-live-session::app.provider_controls')</h2><p class="mt-1 text-xs font-semibold text-slate-500">@lang('teacher-live-session::app.native_always_enabled')</p><div class="mt-4 grid gap-3 sm:grid-cols-3"><div class="rounded-xl border border-green-200 bg-green-50 p-4"><p class="font-black text-green-800">Auronsoft Live</p><span class="mt-2 inline-flex text-xs font-black text-green-700">@lang('teacher-live-session::app.always_enabled')</span></div>@foreach(['google_meet' => 'Google Meet','zoom' => 'Zoom'] as $key => $label)<label class="flex items-center justify-between rounded-xl border border-slate-200 p-4"><span class="font-black text-slate-800">{{ $label }}</span><input type="checkbox" name="live_{{ $key }}_enabled" value="1" @checked($settings['live_'.$key.'_enabled']) class="h-5 w-5 accent-green-600"></label>@endforeach</div></section>
        <section class="rounded-2xl border border-slate-200 bg-white p-5"><h2 class="font-black text-slate-900">@lang('teacher-live-session::app.capacity_limits')</h2><div class="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">@foreach(['live_max_participants','live_max_duration_minutes','live_max_sessions_per_teacher_daily','live_max_bitrate_kbps','live_recording_max_minutes','live_data_retention_days','live_recording_retention_days'] as $key)<label><span class="mb-1.5 block text-xs font-black text-slate-500">@lang('teacher-live-session::app.'.$key)</span><input type="number" name="{{ $key }}" value="{{ old($key, $settings[$key]) }}" min="1" class="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm font-bold"></label>@endforeach</div></section>
        <section class="rounded-2xl border border-slate-200 bg-white p-5"><h2 class="font-black text-slate-900">@lang('teacher-live-session::app.recording_policy')</h2><div class="mt-4 grid gap-3 sm:grid-cols-2">@foreach(['live_recording_enabled','live_recording_consent_required'] as $key)<label class="flex items-center justify-between rounded-xl border border-slate-200 p-4"><span class="font-black text-slate-800">@lang('teacher-live-session::app.'.$key)</span><input type="checkbox" name="{{ $key }}" value="1" @checked($settings[$key]) class="h-5 w-5 accent-green-600"></label>@endforeach</div></section>
        <div class="flex justify-end"><button class="h-11 rounded-xl bg-green-600 px-6 text-sm font-black text-white">@lang('teacher-live-session::app.save_configuration')</button></div>
    </form>
</div></div>
@endsection
