@extends('Mindigo-dashboard::layouts')
@section('title', __('teacher-live-session::app.provider_health_title'))
@section('content')
<div class="min-h-screen bg-slate-50 p-6"><div class="mx-auto max-w-6xl">
    <p class="text-xs font-black uppercase tracking-wider text-green-700">Auronsoft Live</p>
    <div class="flex items-center justify-between gap-4"><h1 class="mt-1 text-2xl font-black text-slate-950">@lang('teacher-live-session::app.provider_health_title')</h1><a href="{{ route('admin.live-providers.configuration') }}" class="inline-flex h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-black text-slate-700 no-underline"><x-heroicon-o-cog-6-tooth class="h-4 w-4" />@lang('teacher-live-session::app.configuration_title')</a></div>
    <p class="mt-1 text-sm font-semibold text-slate-500">@lang('teacher-live-session::app.provider_health_subtitle')</p>
    @if($alerts)<section aria-labelledby="live-operational-alerts" class="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4"><h2 id="live-operational-alerts" class="text-sm font-black text-amber-900">@lang('teacher-live-session::app.operational_alerts')</h2><div class="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">@foreach($alerts as $alert)<div class="rounded-xl bg-white px-3 py-2 text-xs font-bold {{ $alert['severity'] === 'critical' ? 'text-red-700' : 'text-amber-800' }}">{{ __('teacher-live-session::app.alert_'.$alert['code'], ['count' => $alert['count']]) }}</div>@endforeach</div></section>@endif
    <div class="mt-6 grid gap-4 lg:grid-cols-3">
        @foreach($health as $item)
        <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <div class="flex items-start justify-between gap-3"><div><h2 class="font-black text-slate-900">{{ str($item['provider']->value)->replace('_', ' ')->title() }}</h2><p class="text-xs font-bold text-slate-400">{{ $item['provider']->value === 'native' ? __('teacher-live-session::app.default_provider') : __('teacher-live-session::app.external_provider') }}</p></div><span class="rounded-full px-2.5 py-1 text-xs font-black {{ $item['available'] ? 'bg-green-50 text-green-700' : ($item['enabled'] ? 'bg-red-50 text-red-700' : 'bg-slate-100 text-slate-600') }}">{{ $item['available'] ? __('teacher-live-session::app.healthy') : ($item['enabled'] ? __('teacher-live-session::app.unavailable') : __('teacher-live-session::app.disabled')) }}</span></div>
            <dl class="mt-5 grid grid-cols-2 gap-3 border-t border-slate-100 pt-4 text-sm"><div><dt class="text-xs font-bold text-slate-400">@lang('teacher-live-session::app.pending_sync')</dt><dd class="font-black">{{ $item['pending'] }}</dd></div><div><dt class="text-xs font-bold text-slate-400">@lang('teacher-live-session::app.failed_sync')</dt><dd class="font-black">{{ $item['failed'] }}</dd></div><div><dt class="text-xs font-bold text-slate-400">@lang('teacher-live-session::app.failures')</dt><dd class="font-black">{{ $item['circuit']['failures'] }}</dd></div><div><dt class="text-xs font-bold text-slate-400">Circuit</dt><dd class="font-black {{ $item['circuit']['available'] ? 'text-green-700' : 'text-red-700' }}">{{ $item['circuit']['available'] ? 'Closed' : 'Open' }}</dd></div></dl>
            <div class="mt-4 flex flex-wrap gap-1.5">@foreach($item['capabilities'] as $capability => $supported)<span class="rounded-full px-2 py-1 text-[10px] font-black {{ $supported ? 'bg-green-50 text-green-700' : 'bg-slate-100 text-slate-400' }}">{{ str($capability)->replace('_', ' ')->title() }}</span>@endforeach</div><p class="mt-3 text-xs font-bold text-slate-500">{{ $item['monthly_sessions'] }} @lang('teacher-live-session::app.sessions_this_month') · {{ $item['connections'] }} @lang('teacher-live-session::app.oauth_connections')</p>
            @if($item['provider']->isExternal() && !$item['circuit']['available'])<form method="POST" action="{{ route('admin.live-providers.health.reset', $item['provider']->value) }}" class="mt-4">@csrf<button class="h-9 w-full rounded-xl border border-slate-200 text-xs font-black text-slate-700">@lang('teacher-live-session::app.reset_circuit')</button></form>@endif
        </article>
        @endforeach
    </div>
    <section class="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div class="border-b border-slate-100 px-5 py-4"><h2 class="font-black text-slate-900">@lang('teacher-live-session::app.redacted_error_log')</h2><p class="mt-1 text-xs font-semibold text-slate-500">@lang('teacher-live-session::app.redacted_error_hint')</p></div><div class="divide-y divide-slate-100">@forelse($recentErrors as $error)<div class="grid gap-2 px-5 py-3 text-xs sm:grid-cols-[9rem_10rem_1fr]"><span class="font-black text-slate-700">{{ str($error['provider'])->replace('_', ' ')->title() }}</span><span class="font-semibold text-slate-400">{{ $error['at']?->format('d/m/Y H:i') }}</span><span class="break-all font-mono text-slate-600">{{ $error['message'] }}</span></div>@empty<p class="px-5 py-10 text-center text-sm font-semibold text-slate-400">@lang('teacher-live-session::app.no_provider_errors')</p>@endforelse</div></section>
</div></div>
@endsection
