@extends('Mindigo-dashboard::layouts')

@section('title', $course->name.' - Auronsoft LMS')
@section('styles')
    @vite(['packages/Mindigo/Dashboard/src/resources/css/app.css', 'packages/Mindigo/Dashboard/src/resources/js/app.js'])
@endsection

@section('content')
<div class="min-h-screen bg-slate-50">
    <header class="border-b border-slate-200 bg-white px-5 py-4 sm:px-6"><div class="flex items-center justify-between gap-4"><div class="min-w-0"><p class="text-[11px] font-black uppercase tracking-widest text-green-700">@lang('teacher-course::learning.learning_workspace')</p><h1 class="mt-0.5 truncate text-lg font-black text-slate-950">{{ $course->name }}</h1><p class="text-xs font-semibold text-slate-400">@lang('teacher-course::learning.workspace_subtitle')</p></div><a href="{{ route('student.courses.index') }}" aria-label="@lang('teacher-course::learning.back_to_courses')" class="grid h-10 w-10 place-items-center rounded-full border border-slate-200 bg-white text-slate-600"><x-heroicon-o-arrow-left class="h-5 w-5" /></a></div></header>
    <main class="p-4 sm:p-6"><div class="mx-auto grid max-w-6xl gap-5 lg:grid-cols-[minmax(0,1fr)_300px]">
        <div class="space-y-5">
            <section class="rounded-xl border border-slate-200 bg-white p-5"><div class="flex flex-wrap items-center justify-between gap-4"><div><span class="text-[10px] font-black uppercase text-green-700">@lang('teacher-course::learning.overall_progress')</span><p class="mt-1 text-3xl font-black text-slate-950">{{ $enrollment->completion_percentage }}%</p></div>@if($continueLesson)<a href="{{ route('student.courses.lessons.show', [$course->slug, $continueLesson->id]) }}" class="inline-flex h-10 items-center gap-2 rounded-lg bg-green-600 px-5 text-xs font-black text-white no-underline"><x-heroicon-o-play class="h-4 w-4" />@lang('teacher-course::learning.continue_learning')</a>@endif</div><progress value="{{ $enrollment->completion_percentage }}" max="100" class="mt-4 h-2 w-full accent-green-600"></progress><div class="mt-3 flex flex-wrap gap-4 text-[10px] font-bold text-slate-400"><span>{{ __('teacher-course::learning.time_spent', ['time' => gmdate('H:i:s', $enrollment->time_spent_seconds)]) }}</span><span>{{ __('teacher-course::learning.last_activity', ['time' => $enrollment->last_activity_at?->diffForHumans() ?? '—']) }}</span></div></section>
            <section class="overflow-hidden rounded-xl border border-slate-200 bg-white"><div class="border-b border-slate-200 px-5 py-4"><h2 class="text-base font-black text-slate-950">@lang('teacher-course::catalog.curriculum')</h2></div><div class="divide-y divide-slate-100">@forelse($course->chapters as $chapter)<div class="p-5"><h3 class="text-sm font-black text-slate-800">{{ $chapter->name }}</h3><div class="mt-3 space-y-1">@foreach($chapter->lessons as $lesson)@php $done=$completedLessonIds->contains($lesson->id); $position=$lessons->search(fn($item)=>$item->is($lesson)); $available=$lessons->take($position)->pluck('id')->diff($completedLessonIds)->isEmpty() && (!$lesson->prerequisite_lesson_id || $completedLessonIds->contains($lesson->prerequisite_lesson_id)); @endphp @if($available)<a href="{{ route('student.courses.lessons.show', [$course->slug, $lesson->id]) }}" class="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-bold text-slate-600 no-underline hover:bg-green-50 hover:text-green-700">@if($done)<x-heroicon-o-check-circle class="h-5 w-5 text-green-600" />@else<x-heroicon-o-play-circle class="h-5 w-5 text-slate-400" />@endif<span class="flex-1">{{ $lesson->name }}</span></a>@else<div class="flex items-center gap-3 px-3 py-2.5 text-sm font-bold text-slate-400"><x-heroicon-o-lock-closed class="h-5 w-5" /><span>{{ $lesson->name }}</span></div>@endif @endforeach</div></div>@empty<div class="py-12 text-center text-sm font-semibold text-slate-400">@lang('teacher-course::catalog.curriculum_empty')</div>@endforelse</div></section>
        </div>
        <aside class="rounded-xl border border-slate-200 bg-white p-5 lg:sticky lg:top-5 lg:self-start"><h2 class="text-sm font-black text-slate-950">@lang('teacher-course::learning.course_summary')</h2><dl class="mt-3 divide-y divide-slate-100 text-xs"><div class="flex justify-between py-2.5"><dt class="font-bold text-slate-400">@lang('teacher-course::catalog.lessons')</dt><dd class="font-black">{{ $lessons->count() }}</dd></div><div class="flex justify-between py-2.5"><dt class="font-bold text-slate-400">@lang('teacher-course::learning.completed_lessons')</dt><dd class="font-black">{{ $completedLessonIds->count() }}</dd></div><div class="flex justify-between py-2.5"><dt class="font-bold text-slate-400">@lang('teacher-course::learning.enrollment_status')</dt><dd class="font-black text-green-700">@lang('teacher-course::learning.statuses.'.$enrollment->status)</dd></div></dl></aside>
    </div></main>
</div>
@endsection
