<section class="classroom-card p-5">
    <div class="classroom-section-head"><span>01</span><div><h2>@lang('Mindigo-classroom-management::app.basic_info')</h2><p>@lang('Mindigo-classroom-management::app.basic_info_desc')</p></div></div>
    <div class="classroom-form-grid mt-5">
        <label class="classroom-field"><span>@lang('Mindigo-classroom-management::app.name')</span><input name="name" value="{{ old('name', $classroom->name ?? '') }}" class="classroom-input" required>@error('name')<strong>{{ $message }}</strong>@enderror</label>
        <label class="classroom-field"><span>@lang('Mindigo-classroom-management::app.code')</span><input name="code" value="{{ old('code', $classroom->code ?? '') }}" class="classroom-input" required>@error('code')<strong>{{ $message }}</strong>@enderror</label>
        <label class="classroom-field"><span>@lang('Mindigo-classroom-management::app.teacher')</span><select name="teacher_id" class="classroom-select" @disabled(auth()->user()?->isTeacher() && !auth()->user()?->isAdmin())><option value="">@lang('Mindigo-classroom-management::app.not_set')</option>@foreach($teachers as $teacher)<option value="{{ $teacher->id }}" @selected((string) old('teacher_id', $classroom->teacher_id ?? (auth()->user()?->isTeacher() ? auth()->id() : '')) === (string) $teacher->id)>{{ $teacher->name }} - {{ $teacher->email }}</option>@endforeach</select>@if(auth()->user()?->isTeacher() && !auth()->user()?->isAdmin())<input type="hidden" name="teacher_id" value="{{ auth()->id() }}">@endif @error('teacher_id')<strong>{{ $message }}</strong>@enderror</label>
        <label class="classroom-field"><span>@lang('Mindigo-classroom-management::app.school_year')</span><input name="school_year" value="{{ old('school_year', $classroom->school_year ?? '') }}" class="classroom-input" placeholder="2025-2026">@error('school_year')<strong>{{ $message }}</strong>@enderror</label>
        <label class="classroom-field"><span>@lang('Mindigo-classroom-management::app.status')</span><select name="status" class="classroom-select" required>@foreach($statuses as $status)<option value="{{ $status }}" @selected(old('status', $classroom->status ?? 'active') === $status)>@lang('Mindigo-classroom-management::app.statuses.' . $status)</option>@endforeach</select>@error('status')<strong>{{ $message }}</strong>@enderror</label>
        <label class="classroom-field md:col-span-2"><span>@lang('Mindigo-classroom-management::app.description_field')</span><textarea name="description" class="classroom-textarea">{{ old('description', $classroom->description ?? '') }}</textarea>@error('description')<strong>{{ $message }}</strong>@enderror</label>
    </div>
</section>
