@extends('Mindigo-dashboard::layouts')
@section('title', __('learning-tools::app.scores.title') . ' · Mindigo LMS')
@section('styles') @vite(['packages/Mindigo/Dashboard/src/resources/css/app.css', 'packages/Mindigo/Dashboard/src/resources/js/app.js']) @endsection
@section('content')
<div class="flex min-h-screen flex-col bg-slate-50">@include('learning-tools::partials.header', ['eyebrow' => __('learning-tools::app.eyebrow'), 'title' => __('learning-tools::app.scores.title'), 'subtitle' => __('learning-tools::app.scores.subtitle'), 'actionRoute' => route('learning-tools.academic.index'), 'actionLabel' => __('learning-tools::app.academic.open')])
<main class="grid gap-6 p-6 xl:grid-cols-[minmax(0,420px)_1fr]"><form method="POST" action="{{ route('learning-tools.scores.store') }}" class="space-y-4 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">@csrf
<label class="block text-sm font-black text-slate-700">@lang('learning-tools::app.fields.title')<input name="title" value="{{ old('title') }}" required class="mt-2 h-11 w-full rounded-xl border border-slate-200 px-4 font-semibold"></label>
<label class="block text-sm font-black text-slate-700">@lang('learning-tools::app.scores.combination')<input name="combination_code" list="admission-combinations" value="{{ old('combination_code') }}" required placeholder="A00" class="mt-2 h-11 w-full rounded-xl border border-slate-200 px-4 font-semibold"><datalist id="admission-combinations">@foreach($combinations as $code => $subjects)<option value="{{ $code }}">{{ collect($subjects)->map(fn($subject) => __('learning-tools::app.subjects.' . $subject))->join(' - ') }}</option>@endforeach</datalist><span class="mt-1 block text-xs font-semibold text-slate-400">@lang('learning-tools::app.scores.custom_combination')</span></label>
<div class="grid grid-cols-3 gap-3">@for($index = 0; $index < 3; $index++)<label class="text-xs font-black text-slate-600">{{ __('learning-tools::app.scores.subject_number', ['number' => $index + 1]) }}<input type="number" name="scores[]" value="{{ old('scores.' . $index) }}" min="0" max="10" step="0.01" required class="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 font-semibold"></label>@endfor</div>
<div class="grid grid-cols-2 gap-3"><label class="text-xs font-black text-slate-600">@lang('learning-tools::app.scores.priority')<input type="number" name="priority_score" value="{{ old('priority_score', 0) }}" min="0" max="3" step="0.01" class="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 font-semibold"></label><label class="text-xs font-black text-slate-600">@lang('learning-tools::app.scores.bonus')<input type="number" name="bonus_score" value="{{ old('bonus_score', 0) }}" min="0" max="3" step="0.01" class="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 font-semibold"></label></div>
@if($errors->any())<p class="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{{ $errors->first() }}</p>@endif<button class="w-full rounded-full bg-green-600 px-6 py-3 text-sm font-black text-white">@lang('learning-tools::app.scores.calculate_save')</button><p class="text-xs font-semibold text-slate-400">@lang('learning-tools::app.scores.disclaimer')</p></form>
<section class="space-y-3">@forelse($scenarios as $scenario)<article class="flex items-center justify-between gap-4 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div><p class="text-xs font-black uppercase text-green-700">{{ $scenario->combination_code }}</p><h2 class="mt-1 font-black text-slate-900">{{ $scenario->title }}</h2><p class="mt-2 text-xs font-bold text-slate-400">{{ collect($scenario->subject_scores)->join(' + ') }} + {{ $scenario->priority_score }} + {{ $scenario->bonus_score }}</p></div><div class="flex items-center gap-3"><strong class="text-3xl font-black text-green-600">{{ number_format($scenario->total_score, 2) }}</strong><form method="POST" action="{{ route('learning-tools.scores.destroy', $scenario) }}">@csrf @method('DELETE')<button class="text-red-500"><x-heroicon-o-trash class="h-5 w-5" /></button></form></div></article>@empty<div class="rounded-3xl border border-dashed border-slate-300 bg-white py-16 text-center"><p class="font-black text-slate-600">@lang('learning-tools::app.scores.empty')</p></div>@endforelse</section></main></div>
@endsection
