@extends('Mindigo-dashboard::layouts')
@section('title', __('student-practice::app.sets.title').' - Mindigo LMS')
@section('styles') @vite(['packages/Mindigo/Dashboard/src/resources/css/app.css', 'packages/Mindigo/Dashboard/src/resources/js/app.js']) @endsection
@section('content')
<main class="min-h-screen bg-slate-50 px-4 py-6 sm:px-6 lg:px-8"><div class="mx-auto flex w-full max-w-[1500px] flex-col gap-6">
<header class="flex flex-col gap-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:flex-row lg:items-center lg:justify-between"><div><p class="text-[11px] font-black uppercase tracking-[0.16em] text-green-700">@lang('student-practice::app.area')</p><h1 class="mt-1 text-3xl font-black text-slate-950">@lang('student-practice::app.sets.title')</h1><p class="mt-2 max-w-3xl text-sm font-semibold leading-6 text-slate-500">@lang('student-practice::app.sets.subtitle')</p></div><a href="{{ route('student.practice.index') }}" class="inline-flex h-11 items-center justify-center rounded-xl border border-slate-200 px-4 text-sm font-black text-slate-700 no-underline hover:bg-slate-50">@lang('student-practice::app.sets.quick_practice')</a></header>
@if($errors->any())<div role="alert" class="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-700">{{ $errors->first() }}</div>@endif @if(session('success'))<div class="rounded-xl border border-green-200 bg-green-50 p-4 text-sm font-bold text-green-700">{{ session('success') }}</div>@endif
<div class="grid gap-6 xl:grid-cols-[24rem_minmax(0,1fr)]"><section class="self-start rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-lg font-black text-slate-950">@lang('student-practice::app.sets.create')</h2><p class="mt-1 text-xs font-semibold leading-5 text-slate-500">@lang('student-practice::app.sets.create_hint')</p><form action="{{ route('student.practice.sets.store') }}" method="POST" class="mt-5 space-y-4">@csrf @php($field = 'mt-1 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm font-bold text-slate-700 outline-none focus:border-green-300 focus:ring-4 focus:ring-green-50')
<label class="block text-xs font-black text-slate-600">@lang('student-practice::app.sets.name')<input name="title" value="{{ old('title') }}" required class="{{ $field }}"></label><label class="block text-xs font-black text-slate-600">@lang('student-practice::app.sets.description')<textarea name="description" rows="2" class="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm font-bold">{{ old('description') }}</textarea></label><label class="block text-xs font-black text-slate-600">@lang('student-practice::app.sets.source')<select name="source" class="{{ $field }}">@foreach(['manual','mistakes','weak_topics'] as $source)<option value="{{ $source }}">@lang('student-practice::app.sets.sources.'.$source)</option>@endforeach</select></label>
<div class="grid grid-cols-2 gap-3"><label class="block text-xs font-black text-slate-600">@lang('student-practice::app.subject')<select name="subject" class="{{ $field }}"><option value="">@lang('student-practice::app.all')</option>@foreach($formData['subjects'] as $subject)<option value="{{ $subject }}">{{ $subject }}</option>@endforeach</select></label><label class="block text-xs font-black text-slate-600">@lang('student-practice::app.topic')<input name="topic" value="{{ old('topic') }}" class="{{ $field }}"></label></div><label class="block text-xs font-black text-slate-600">@lang('student-practice::app.skills.singular')<select name="skill_id" class="{{ $field }}"><option value="">@lang('student-practice::app.sets.weakest_skill')</option>@foreach($formData['skills'] as $skill)<option value="{{ $skill->id }}">{{ $skill->subject?->name }} · {{ $skill->name }}</option>@endforeach</select></label>
<div class="grid grid-cols-2 gap-3"><label class="block text-xs font-black text-slate-600">@lang('student-practice::app.difficulty')<select name="difficulty" class="{{ $field }}"><option value="">@lang('student-practice::app.all')</option>@foreach(['easy','medium','hard'] as $difficulty)<option value="{{ $difficulty }}">@lang('student-practice::app.difficulties.'.$difficulty)</option>@endforeach</select></label><label class="block text-xs font-black text-slate-600">@lang('student-practice::app.question_count')<input type="number" name="question_count" min="1" max="50" value="{{ old('question_count', 10) }}" class="{{ $field }}"></label></div><button class="inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-green-600 px-4 text-sm font-black text-white hover:bg-green-700"><x-heroicon-o-bookmark class="h-4 w-4" />@lang('student-practice::app.sets.save')</button></form></section>
<section><div class="mb-4 flex items-center justify-between"><div><h2 class="text-xl font-black text-slate-950">@lang('student-practice::app.sets.library')</h2><p class="mt-1 text-sm font-semibold text-slate-500">@lang('student-practice::app.sets.library_hint')</p></div><span class="rounded-full bg-green-50 px-3 py-1 text-xs font-black text-green-700">{{ $sets->total() }}</span></div><div class="grid gap-4 md:grid-cols-2">@forelse($sets as $set)<article class="flex flex-col rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex justify-between gap-3"><span class="rounded-full bg-sky-50 px-3 py-1 text-[11px] font-black text-sky-700">@lang('student-practice::app.sets.sources.'.$set->source)</span><span class="text-xs font-black text-slate-400">{{ $set->questions_count }} @lang('student-practice::app.sets.questions')</span></div><h3 class="mt-4 text-base font-black text-slate-950">{{ $set->title }}</h3><p class="mt-2 line-clamp-2 min-h-10 text-sm font-semibold leading-5 text-slate-500">{{ $set->description ?: __('student-practice::app.sets.no_description') }}</p><a href="{{ route('student.practice.sets.show', $set) }}" class="mt-5 inline-flex h-10 items-center justify-center rounded-xl bg-slate-950 px-4 text-xs font-black text-white no-underline hover:bg-green-700">@lang('student-practice::app.sets.open')</a></article>@empty<div class="col-span-full rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-14 text-center"><h3 class="font-black text-slate-800">@lang('student-practice::app.sets.empty')</h3><p class="mt-1 text-sm font-semibold text-slate-400">@lang('student-practice::app.sets.empty_hint')</p></div>@endforelse</div><div class="mt-5">{{ $sets->links() }}</div></section></div></div></main>
@endsection
