@extends('Mindigo-dashboard::layouts')
@section('title', $set->title.' - Mindigo LMS')
@section('styles') @vite(['packages/Mindigo/Dashboard/src/resources/css/app.css', 'packages/Mindigo/Dashboard/src/resources/js/app.js']) @endsection
@section('content')
<main class="min-h-screen bg-slate-50 px-4 py-6 sm:px-6"><div class="mx-auto max-w-6xl space-y-6"><header class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><a href="{{ route('student.practice.sets.index') }}" class="text-xs font-black text-green-700 no-underline">← @lang('student-practice::app.sets.back')</a><div class="mt-4 flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><span class="rounded-full bg-sky-50 px-3 py-1 text-[11px] font-black text-sky-700">@lang('student-practice::app.sets.sources.'.$set->source)</span><h1 class="mt-3 text-3xl font-black text-slate-950">{{ $set->title }}</h1><p class="mt-2 max-w-2xl text-sm font-semibold leading-6 text-slate-500">{{ $set->description }}</p></div><form action="{{ route('student.practice.sets.start', $set) }}" method="POST">@csrf<button class="h-11 rounded-xl bg-green-600 px-6 text-sm font-black text-white">@lang('student-practice::app.sets.start')</button></form></div></header>
@if(session('success'))<div class="rounded-xl border border-green-200 bg-green-50 p-4 text-sm font-bold text-green-700">{{ session('success') }}</div>@endif
<section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h2 class="font-black text-slate-950">{{ trans_choice('student-practice::app.sets.question_total', $set->questions->count(), ['count' => $set->questions->count()]) }}</h2></div><div class="divide-y divide-slate-100">@foreach($set->questions as $index => $question)<div class="flex gap-4 px-5 py-4"><span class="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-green-50 text-xs font-black text-green-700">{{ $index + 1 }}</span><div><p class="text-sm font-bold leading-6 text-slate-800">{{ strip_tags($question->content) }}</p><p class="mt-1 text-xs font-semibold text-slate-400">{{ $question->subject }} · {{ $question->topic }}</p></div></div>@endforeach</div></section>
<section class="grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-[1fr_auto_auto]"><div><h2 class="font-black text-slate-950">@lang('student-practice::app.sets.share')</h2><p class="mt-1 text-xs font-semibold text-slate-500">@lang('student-practice::app.sets.share_hint')</p>@if($set->is_shared)<input readonly value="{{ route('practice.shared', $set->share_token) }}" class="mt-3 h-10 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-xs font-bold">@endif</div><form action="{{ route('student.practice.sets.share', $set) }}" method="POST" class="self-end">@csrf @method('PATCH')<input type="hidden" name="enabled" value="{{ $set->is_shared ? 0 : 1 }}"><button class="h-10 rounded-xl border border-slate-200 px-4 text-xs font-black">{{ $set->is_shared ? __('student-practice::app.sets.stop_share') : __('student-practice::app.sets.enable_share') }}</button></form><form action="{{ route('student.practice.sets.destroy', $set) }}" method="POST" class="self-end">@csrf @method('DELETE')<button class="h-10 rounded-xl bg-rose-50 px-4 text-xs font-black text-rose-700">@lang('student-practice::app.sets.delete')</button></form></section>
</div></main>
@endsection
