@forelse($candidates as $row)
    @php($attempt = $row['attempt'])
    <tr class="border-t border-slate-100 align-top" data-monitor-candidate>
        <td class="px-4 py-4"><strong class="block text-sm text-slate-900">{{ $row['candidate']->name }}</strong><span class="text-xs font-semibold text-slate-400">{{ $row['candidate']->student_code ?: $row['candidate']->email }}</span></td>
        <td class="px-4 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-black {{ in_array($row['monitor_status'], ['in_progress', 'submitted']) ? 'bg-green-50 text-green-700' : ($row['monitor_status'] === 'disconnected' || $row['monitor_status'] === 'terminated' ? 'bg-rose-50 text-rose-700' : 'bg-amber-50 text-amber-700') }}">{{ __('Mindigo-exam-management::app.monitoring.statuses.'.$row['monitor_status']) }}</span></td>
        <td class="px-4 py-4 text-sm font-black text-slate-700" data-remaining="{{ $row['remaining_seconds'] ?? '' }}">{{ $row['remaining_seconds'] === null ? '—' : sprintf('%02d:%02d', intdiv($row['remaining_seconds'], 60), $row['remaining_seconds'] % 60) }}</td>
        <td class="px-4 py-4 text-sm font-semibold text-slate-500">{{ $row['last_activity_at']?->diffForHumans() ?? '—' }}</td>
        <td class="px-4 py-4 text-center text-sm font-black text-slate-700">{{ $row['current_question_number'] ?? '—' }}</td>
        <td class="px-4 py-4 text-center"><span class="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-black text-amber-700">{{ $row['warning_count'] }}</span></td>
        <td class="px-4 py-4 text-center"><strong class="text-sm {{ $row['integrity_score'] >= 80 ? 'text-green-700' : ($row['integrity_score'] >= 50 ? 'text-amber-700' : 'text-rose-700') }}">{{ $row['integrity_score'] }}/100</strong></td>
        <td class="min-w-72 px-4 py-4">
            @if($attempt)<div class="flex flex-wrap gap-2">
                @if(in_array($attempt->status, ['in_progress', 'paused']))<form method="POST" action="{{ route('teacher.exam-sessions.monitoring.add-time', [$session, $attempt]) }}" class="flex">@csrf<input type="number" name="minutes" value="5" min="1" max="180" class="w-14 rounded-l-lg border border-slate-200 px-2 text-xs"><button class="rounded-r-lg bg-slate-800 px-2.5 py-2 text-xs font-black text-white">+ @lang('Mindigo-exam-management::app.monitoring.minutes')</button></form>@endif
                @if($attempt->status === 'in_progress')<form method="POST" action="{{ route('teacher.exam-sessions.monitoring.pause', [$session, $attempt]) }}">@csrf<button class="rounded-lg border border-amber-200 px-3 py-2 text-xs font-black text-amber-700">@lang('Mindigo-exam-management::app.monitoring.pause')</button></form>@elseif($attempt->status === 'paused')<form method="POST" action="{{ route('teacher.exam-sessions.monitoring.resume', [$session, $attempt]) }}">@csrf<button class="rounded-lg bg-green-600 px-3 py-2 text-xs font-black text-white">@lang('Mindigo-exam-management::app.monitoring.resume')</button></form>@endif
                @if(in_array($attempt->status, ['submitted', 'expired', 'terminated']))<form method="POST" action="{{ route('teacher.exam-sessions.monitoring.retry', [$session, $attempt]) }}">@csrf<button class="rounded-lg border border-green-200 px-3 py-2 text-xs font-black text-green-700">@lang('Mindigo-exam-management::app.monitoring.retry')</button></form>@endif
                <details class="relative"><summary class="cursor-pointer list-none rounded-lg border border-slate-200 px-3 py-2 text-xs font-black text-slate-600">@lang('Mindigo-exam-management::app.monitoring.more')</summary><div class="absolute right-0 z-20 mt-2 w-72 space-y-3 rounded-xl border border-slate-200 bg-white p-3 shadow-xl">
                    <form method="POST" action="{{ route('teacher.exam-sessions.monitoring.warning', [$session, $attempt]) }}" class="grid gap-2">@csrf<input name="message" required maxlength="1000" class="exam-input" placeholder="@lang('Mindigo-exam-management::app.monitoring.warning_placeholder')"><button class="rounded-lg bg-amber-500 px-3 py-2 text-xs font-black text-white">@lang('Mindigo-exam-management::app.monitoring.send_warning')</button></form>
                    <form method="POST" action="{{ route('teacher.exam-sessions.proctor.note', [$session, $attempt]) }}" class="grid gap-2">@csrf<input name="note" required maxlength="2000" class="exam-input" placeholder="@lang('Mindigo-exam-management::app.proctoring.note_placeholder')"><button class="rounded-lg border border-slate-200 px-3 py-2 text-xs font-black">@lang('Mindigo-exam-management::app.proctoring.add_note')</button></form>
                    @if(in_array($attempt->status, ['in_progress', 'paused']))<form method="POST" action="{{ route('teacher.exam-sessions.proctor.terminate', [$session, $attempt]) }}" class="grid gap-2" onsubmit="return confirm(@js(__('Mindigo-exam-management::app.monitoring.confirm_terminate')))">@csrf<input name="reason" required maxlength="2000" class="exam-input" placeholder="@lang('Mindigo-exam-management::app.monitoring.termination_reason')"><button class="rounded-lg bg-rose-600 px-3 py-2 text-xs font-black text-white">@lang('Mindigo-exam-management::app.monitoring.terminate')</button></form>@endif
                </div></details>
            </div>@else<span class="text-xs font-semibold text-slate-400">@lang('Mindigo-exam-management::app.monitoring.awaiting_start')</span>@endif
        </td>
    </tr>
@empty
    <tr><td colspan="8" class="px-4 py-12 text-center text-sm font-semibold text-slate-500">@lang('Mindigo-exam-management::app.monitoring.empty')</td></tr>
@endforelse
