<section class="rounded-xl border border-slate-200 bg-white p-5">
    <div class="flex flex-wrap items-end justify-between gap-4"><div><h2 class="text-base font-black text-slate-950">@lang('teacher-course::reviews.title')</h2><p class="mt-1 text-xs font-semibold text-slate-400">{{ __('teacher-course::reviews.summary', ['count' => $course->rating_count]) }}</p></div><p class="text-3xl font-black text-amber-500">{{ number_format($course->rating_average, 1) }} <span class="text-lg">★</span></p></div>
    <div class="mt-4 grid gap-2 sm:grid-cols-5">@foreach(array_reverse($course->rating_distribution, true) as $star => $count)<div class="rounded-lg bg-slate-50 p-2 text-center"><p class="text-xs font-black text-amber-500">{{ $star }} ★</p><p class="text-[10px] font-bold text-slate-400">{{ __('teacher-course::reviews.distribution', ['count' => $count]) }}</p></div>@endforeach</div>
    @if(auth()->user()?->isStudent())
        @php $reviewEnrollment = $course->enrollments->first(); $ownReview = $reviewEnrollment?->review; $canReview = $reviewEnrollment && ($reviewEnrollment->status === \Mindigo\TeacherCourse\Models\CourseEnrollment::STATUS_COMPLETED || $reviewEnrollment->completion_percentage >= config('course.review_minimum_completion_percentage', 100)); @endphp
        @if($canReview)<form method="POST" action="{{ $ownReview ? route('courses.reviews.update', [$course, $ownReview]) : route('courses.reviews.store', $course) }}" class="mt-5 rounded-lg border border-slate-200 bg-slate-50 p-4">@csrf @if($ownReview) @method('PUT') @endif<h3 class="text-sm font-black text-slate-900">@lang('teacher-course::reviews.your_review')</h3><div class="mt-3 grid gap-3 sm:grid-cols-[140px_minmax(0,1fr)]"><select name="rating" required class="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm">@foreach(range(5, 1) as $star)<option value="{{ $star }}" @selected(old('rating', $ownReview?->rating) == $star)>{{ $star }} ★</option>@endforeach</select><textarea name="comment" rows="3" maxlength="2000" placeholder="{{ __('teacher-course::reviews.comment_placeholder') }}" class="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm">{{ old('comment', $ownReview?->comment) }}</textarea></div><div class="mt-3 flex justify-end"><button class="rounded-lg bg-green-600 px-4 py-2 text-xs font-black text-white">{{ $ownReview ? __('teacher-course::reviews.update') : __('teacher-course::reviews.submit') }}</button></div></form>@endif
    @endif
    <div class="mt-5 divide-y divide-slate-100">@forelse($course->reviews as $review)<article class="py-4"><div class="flex items-start justify-between gap-3"><div><p class="font-black text-slate-900">{{ $review->student->name }}</p><p class="text-xs font-black text-amber-500">{{ str_repeat('★', $review->rating) }}</p></div><time class="text-[10px] font-bold text-slate-400">{{ $review->updated_at->diffForHumans() }}</time></div>@if($review->comment)<p class="mt-2 text-sm font-semibold leading-6 text-slate-600">{{ $review->comment }}</p>@endif
        @if($review->teacher_reply)<div class="mt-3 rounded-lg border-l-4 border-green-500 bg-green-50 p-3"><p class="text-[10px] font-black uppercase text-green-700">@lang('teacher-course::reviews.teacher_reply')</p><p class="mt-1 text-sm font-semibold text-slate-600">{{ $review->teacher_reply }}</p></div>@endif
        @can('reply', $review)<form method="POST" action="{{ route('course-reviews.reply', $review) }}" class="mt-3 flex gap-2">@csrf<input name="teacher_reply" required maxlength="2000" value="{{ $review->teacher_reply }}" placeholder="{{ __('teacher-course::reviews.reply_placeholder') }}" class="min-w-0 flex-1 rounded-lg border border-slate-200 px-3 py-2 text-xs"><button class="rounded-lg border border-green-200 px-3 text-xs font-black text-green-700">@lang('teacher-course::reviews.reply')</button></form>@endcan
        @if(auth()->user()?->isAdmin())<form method="POST" action="{{ route('admin.course-reviews.moderate', $review) }}" class="mt-2 flex gap-2">@csrf @method('PATCH')<input type="hidden" name="moderation_status" value="hidden"><input name="moderation_reason" required placeholder="{{ __('teacher-course::reviews.reason') }}" class="min-w-0 flex-1 rounded-lg border border-slate-200 px-3 py-2 text-xs"><button class="rounded-lg border border-red-200 px-3 text-xs font-black text-red-600">@lang('teacher-course::reviews.hide')</button></form>@endif
    </article>@empty<p class="py-10 text-center text-sm font-semibold text-slate-400">@lang('teacher-course::reviews.empty')</p>@endforelse</div>
</section>
