@php
    $labels = [
        'connected' => __('teacher-live-session::app.media_connected'),
        'reconnecting' => __('teacher-live-session::app.media_reconnecting'),
        'permissionDenied' => __('teacher-live-session::app.media_permission_denied'),
        'deviceNotFound' => __('teacher-live-session::app.media_device_not_found'),
        'deviceBusy' => __('teacher-live-session::app.media_device_busy'),
        'secureContextRequired' => __('teacher-live-session::app.media_secure_context_required'),
        'microphoneOn' => __('teacher-live-session::app.microphone_on'),
        'microphoneOff' => __('teacher-live-session::app.microphone_off'),
        'cameraOn' => __('teacher-live-session::app.camera_on'),
        'cameraOff' => __('teacher-live-session::app.camera_off'),
        'screenSharing' => __('teacher-live-session::app.screen_sharing'),
        'screenShareStopped' => __('teacher-live-session::app.screen_share_stopped'),
        'shareScreen' => __('teacher-live-session::app.share_screen'),
        'stopScreenShare' => __('teacher-live-session::app.stop_screen_share'),
        'handRaised' => __('teacher-live-session::app.hand_raised'),
        'raiseHand' => __('teacher-live-session::app.raise_hand'),
        'lowerHand' => __('teacher-live-session::app.lower_hand'),
        'reactionSent' => __('teacher-live-session::app.reaction_sent'),
        'mutedByModerator' => __('teacher-live-session::app.muted_by_moderator'),
        'you' => __('teacher-live-session::app.you'),
        'startRecording' => __('teacher-live-session::app.start_recording'),
        'stopRecording' => __('teacher-live-session::app.stop_recording'),
        'recordingFailed' => __('teacher-live-session::app.recording_failed'),
        'recordingProcessing' => __('teacher-live-session::app.recording_processing'),
        'recordingProcessed' => __('teacher-live-session::app.recording_processed'),
        'noPoll' => __('teacher-live-session::app.no_poll'),
        'noResources' => __('teacher-live-session::app.no_resources'),
        'closePoll' => __('teacher-live-session::app.close_poll'),
        'mainRoom' => __('teacher-live-session::app.main_room'),
        'noBreakoutRooms' => __('teacher-live-session::app.no_breakout_rooms'),
        'visitRoom' => __('teacher-live-session::app.visit_room'),
        'prejoinReady' => __('teacher-live-session::app.prejoin_ready'),
        'prejoinTesting' => __('teacher-live-session::app.prejoin_testing'),
        'speakerTest' => __('teacher-live-session::app.speaker_test_playing'),
        'captionsOn' => __('teacher-live-session::app.captions_on'),
        'captionsOff' => __('teacher-live-session::app.captions_off'),
        'captionsUnsupported' => __('teacher-live-session::app.captions_unsupported'),
        'enableCaptions' => __('teacher-live-session::app.enable_captions'),
        'disableCaptions' => __('teacher-live-session::app.disable_captions'),
    ];
    $clientConfig = [...$mediaConfig, 'labels' => $labels];
    $displayName = $displayName ?? auth()->user()?->name ?? __('teacher-live-session::app.external_guest');
    $collaborationEnabled = filled($mediaConfig['collaborationSyncUrl'] ?? null);
@endphp
<section data-live-media-room='@json($clientConfig)' aria-label="@lang('teacher-live-session::app.live_room')" class="relative flex min-h-0 flex-1 flex-col overflow-hidden rounded-2xl border border-slate-200 bg-slate-950 shadow-sm">
    <div data-prejoin role="dialog" aria-modal="true" aria-labelledby="prejoin-title" class="absolute inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-950 p-4 sm:p-6">
        <div class="grid w-full max-w-5xl gap-5 rounded-3xl border border-white/10 bg-slate-900 p-5 shadow-2xl lg:grid-cols-[minmax(0,1.35fr)_minmax(300px,.65fr)]">
            <div class="relative min-h-72 overflow-hidden rounded-2xl bg-slate-950 ring-1 ring-white/10">
                <video data-prejoin-video autoplay muted playsinline class="h-full w-full object-cover"></video>
                <div data-prejoin-placeholder class="absolute inset-0 grid place-items-center"><span class="grid h-20 w-20 place-items-center rounded-full bg-green-600 text-2xl font-black text-white">{{ mb_strtoupper(mb_substr($displayName, 0, 1)) }}</span></div>
                <div class="absolute inset-x-0 bottom-0 flex items-center justify-between bg-slate-950/80 px-4 py-3 text-xs font-bold text-white"><span>{{ $displayName }}</span><span data-prejoin-meter aria-label="@lang('teacher-live-session::app.microphone_level')" class="h-2 w-24 overflow-hidden rounded-full bg-white/20"><span class="block h-full w-0 rounded-full bg-green-400 transition-[width]"></span></span></div>
            </div>
            <div class="flex flex-col">
                <div><p class="text-xs font-black uppercase tracking-widest text-green-400">Mindigo Live</p><h2 id="prejoin-title" class="mt-1 text-xl font-black text-white">@lang('teacher-live-session::app.prejoin_title')</h2><p class="mt-1 text-sm font-semibold text-slate-400">@lang('teacher-live-session::app.prejoin_hint')</p></div>
                <div class="mt-5 space-y-3">
                    <label class="block text-xs font-bold text-slate-300"><span>@lang('teacher-live-session::app.camera')</span><select data-prejoin-camera class="mt-1 h-11 w-full rounded-xl border border-white/10 bg-slate-800 px-3 text-sm text-white focus:border-green-500 focus:outline-none"></select></label>
                    <label class="block text-xs font-bold text-slate-300"><span>@lang('teacher-live-session::app.microphone')</span><select data-prejoin-microphone class="mt-1 h-11 w-full rounded-xl border border-white/10 bg-slate-800 px-3 text-sm text-white focus:border-green-500 focus:outline-none"></select></label>
                    <label class="block text-xs font-bold text-slate-300"><span>@lang('teacher-live-session::app.virtual_background')</span><select data-prejoin-background class="mt-1 h-11 w-full rounded-xl border border-white/10 bg-slate-800 px-3 text-sm text-white focus:border-green-500 focus:outline-none"><option value="none">@lang('teacher-live-session::app.background_none')</option><option value="soft">@lang('teacher-live-session::app.background_soft')</option><option value="focus">@lang('teacher-live-session::app.background_focus')</option></select></label>
                </div>
                <div class="mt-4 grid grid-cols-3 gap-2"><button type="button" data-prejoin-microphone-toggle aria-pressed="true" class="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-green-600 px-3 text-xs font-black text-white"><x-heroicon-o-microphone class="h-4 w-4" />@lang('teacher-live-session::app.microphone')</button><button type="button" data-prejoin-camera-toggle aria-pressed="true" class="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-green-600 px-3 text-xs font-black text-white"><x-heroicon-o-video-camera class="h-4 w-4" />@lang('teacher-live-session::app.camera')</button><button type="button" data-test-speaker class="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-slate-700 px-3 text-xs font-black text-white hover:bg-slate-600"><x-heroicon-o-speaker-wave class="h-4 w-4" />@lang('teacher-live-session::app.test_speaker')</button></div>
                <p data-prejoin-status role="status" aria-live="polite" class="mt-4 min-h-5 text-xs font-semibold text-slate-400">@lang('teacher-live-session::app.prejoin_testing')</p>
                <button type="button" data-enter-room class="mt-auto h-12 rounded-xl bg-green-600 px-5 text-sm font-black text-white shadow-lg shadow-green-950/30 hover:bg-green-500 focus:outline-none focus:ring-2 focus:ring-green-300">@lang('teacher-live-session::app.enter_room')</button>
            </div>
        </div>
    </div>
    <div class="flex items-center justify-between border-b border-white/10 px-4 py-3 text-white">
        <div class="flex items-center gap-2 text-xs font-bold"><span class="h-2 w-2 rounded-full bg-green-400"></span><span data-media-status role="status" aria-live="polite">@lang('teacher-live-session::app.media_connecting')</span></div>
        <div class="flex items-center gap-2"><div class="flex items-center rounded-xl bg-white/10 p-1" role="group" aria-label="@lang('teacher-live-session::app.layout_mode')"><button type="button" data-layout-mode="grid" aria-pressed="true" title="@lang('teacher-live-session::app.layout_grid')" class="grid h-8 w-8 place-items-center rounded-lg bg-white text-slate-900"><x-heroicon-o-squares-2x2 class="h-4 w-4" /></button><button type="button" data-layout-mode="speaker" aria-pressed="false" title="@lang('teacher-live-session::app.layout_speaker')" class="grid h-8 w-8 place-items-center rounded-lg text-white"><x-heroicon-o-rectangle-group class="h-4 w-4" /></button><button type="button" data-layout-mode="sidebar" aria-pressed="false" title="@lang('teacher-live-session::app.layout_sidebar')" class="grid h-8 w-8 place-items-center rounded-lg text-white"><x-heroicon-o-view-columns class="h-4 w-4" /></button><button type="button" data-layout-mode="classroom" aria-pressed="false" title="@lang('teacher-live-session::app.layout_classroom')" class="grid h-8 w-8 place-items-center rounded-lg text-white"><x-heroicon-o-academic-cap class="h-4 w-4" /></button></div><span data-recording-indicator class="hidden items-center gap-2 rounded-full bg-red-600 px-3 py-1 text-xs font-black"><span class="h-2 w-2 animate-pulse rounded-full bg-white"></span>REC <span data-recording-time>00:00</span></span></div>
        @if($collaborationEnabled)<button type="button" data-toggle-collaboration class="inline-flex items-center gap-1.5 rounded-full bg-white/10 px-3 py-1 text-xs font-bold"><x-heroicon-o-user-group class="h-4 w-4" /><span data-participant-count>1</span></button>@else<span class="inline-flex items-center gap-1.5 rounded-full bg-white/10 px-3 py-1 text-xs font-bold"><x-heroicon-o-user-group class="h-4 w-4" /><span data-participant-count>1</span></span>@endif
    </div>
    <div data-remote-grid class="grid min-h-0 flex-1 content-start justify-center gap-3 overflow-y-auto p-3">
        <section data-classroom-stage class="hidden grid-cols-[minmax(0,1fr)_240px] items-end gap-6 rounded-3xl border border-green-900/50 bg-green-950/30 p-5 shadow-inner"><div data-classroom-projection-slot class="min-w-0"></div><div class="flex flex-col items-center"><div data-classroom-teacher-slot class="w-full"></div><div class="relative mt-3 h-20 w-48 rounded-t-xl border-x-8 border-t-8 border-amber-800 bg-amber-700 shadow-xl"><div class="absolute inset-x-3 top-3 rounded-lg bg-amber-600 px-3 py-2 text-center text-xs font-black text-amber-50">@lang('teacher-live-session::app.teacher_podium')</div></div></div></section>
        <section data-classroom-projector class="relative hidden min-h-64 overflow-hidden rounded-2xl border-8 border-slate-700 bg-slate-100 shadow-2xl" aria-label="@lang('teacher-live-session::app.classroom_projector')"><div class="absolute inset-x-0 top-0 h-2 bg-slate-800"></div><div class="grid h-full min-h-64 place-items-center text-center"><div><span class="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-green-50 text-green-700"><x-heroicon-o-computer-desktop class="h-7 w-7" /></span><p class="mt-4 text-sm font-black text-slate-700">@lang('teacher-live-session::app.classroom_projector')</p><p class="mt-1 text-xs font-semibold text-slate-400">@lang('teacher-live-session::app.classroom_projector_hint')</p></div></div><div class="absolute bottom-0 left-1/2 h-5 w-24 -translate-x-1/2 translate-y-3 rounded-b bg-slate-700"></div></section>
        <article data-participant-tile data-self-tile data-participant-role="{{ $mediaConfig['participantRole'] ?? 'student' }}" class="relative aspect-video w-full overflow-hidden rounded-2xl bg-slate-900 ring-1 ring-white/10">
            <video data-local-video autoplay muted playsinline class="hidden h-full w-full object-cover"></video>
            <div data-local-placeholder class="grid h-full min-h-48 place-items-center"><span class="grid h-16 w-16 place-items-center rounded-full bg-green-600 text-xl font-black text-white">{{ mb_strtoupper(mb_substr($displayName, 0, 1)) }}</span></div>
            <div class="absolute inset-x-0 bottom-0 flex items-center justify-between bg-slate-950/70 px-3 py-2 text-xs font-bold text-white"><span>{{ $displayName }} (@lang('teacher-live-session::app.you'))</span></div>
        </article>
        <article data-screen-preview class="relative hidden aspect-video w-full overflow-hidden rounded-2xl border-8 border-slate-700 bg-slate-900 shadow-2xl ring-2 ring-green-500">
            <video data-screen-preview-video autoplay muted playsinline class="h-full w-full object-contain"></video>
            <div class="absolute inset-x-0 bottom-0 flex items-center gap-2 bg-slate-950/80 px-3 py-2 text-xs font-black text-white"><span class="h-2 w-2 animate-pulse rounded-full bg-green-400"></span>@lang('teacher-live-session::app.you_are_sharing_screen')</div>
        </article>
    </div>
    <div data-live-caption role="status" aria-live="polite" aria-atomic="true" class="pointer-events-none absolute inset-x-4 bottom-20 z-20 hidden justify-center"><p class="max-w-3xl rounded-xl bg-slate-950/90 px-5 py-3 text-center text-base font-bold leading-6 text-white shadow-xl"></p></div>
    <div class="flex flex-wrap items-center justify-center gap-2 border-t border-white/10 bg-slate-900 px-4 py-3">
        <button type="button" data-toggle-microphone data-active="false" aria-pressed="false" class="inline-flex h-11 items-center gap-2 rounded-xl bg-slate-700 px-4 text-xs font-black text-white hover:bg-slate-600 disabled:cursor-wait disabled:opacity-60"><span data-media-icon-on class="hidden"><x-heroicon-o-microphone class="h-5 w-5" /></span><span data-media-icon-off class="relative"><x-heroicon-o-microphone class="h-5 w-5" /><span class="absolute left-1/2 top-1/2 h-0.5 w-6 -translate-x-1/2 -translate-y-1/2 -rotate-45 rounded bg-red-400"></span></span><span>@lang('teacher-live-session::app.microphone')</span></button>
        <button type="button" data-toggle-camera data-active="false" aria-pressed="false" class="inline-flex h-11 items-center gap-2 rounded-xl bg-slate-700 px-4 text-xs font-black text-white hover:bg-slate-600 disabled:cursor-wait disabled:opacity-60"><span data-media-icon-on class="hidden"><x-heroicon-o-video-camera class="h-5 w-5" /></span><span data-media-icon-off><x-heroicon-o-video-camera-slash class="h-5 w-5 text-red-300" /></span><span>@lang('teacher-live-session::app.camera')</span></button>
        <button type="button" data-toggle-screen data-active="false" aria-pressed="false" class="inline-flex h-11 items-center gap-2 rounded-xl bg-slate-700 px-4 text-xs font-black text-white hover:bg-slate-600 disabled:cursor-wait disabled:opacity-60"><x-heroicon-o-computer-desktop class="h-5 w-5" /><span data-screen-button-label>@lang('teacher-live-session::app.share_screen')</span></button>
        <button type="button" data-toggle-captions data-active="false" aria-pressed="false" class="inline-flex h-11 items-center gap-2 rounded-xl bg-slate-700 px-4 text-xs font-black text-white hover:bg-slate-600"><x-heroicon-o-chat-bubble-bottom-center-text class="h-5 w-5" /><span data-caption-label>@lang('teacher-live-session::app.enable_captions')</span></button>
        @if(filled($mediaConfig['teachingToolsSyncUrl'] ?? null))<button type="button" data-toggle-teaching-tools class="inline-flex h-11 items-center gap-2 rounded-xl bg-white/10 px-4 text-xs font-black text-white hover:bg-white/20"><x-heroicon-o-academic-cap class="h-5 w-5" />@lang('teacher-live-session::app.teaching_tools')</button>@endif
        @if(filled($mediaConfig['breakoutSyncUrl'] ?? null))<button type="button" data-toggle-breakouts class="inline-flex h-11 items-center gap-2 rounded-xl bg-white/10 px-4 text-xs font-black text-white hover:bg-white/20"><x-heroicon-o-squares-2x2 class="h-5 w-5" />@lang('teacher-live-session::app.breakout_rooms')</button>@endif
        @if(($mediaConfig['recordingEnabled'] ?? false) && ($mediaConfig['canRecord'] ?? false))<button type="button" data-toggle-recording data-active="false" class="inline-flex h-11 items-center gap-2 rounded-xl bg-red-600 px-4 text-xs font-black text-white hover:bg-red-500"><span class="h-3 w-3 rounded-full bg-white"></span><span data-recording-label>@lang('teacher-live-session::app.start_recording')</span></button>@endif
        @if($collaborationEnabled)<button type="button" data-toggle-hand data-active="false" aria-pressed="false" class="inline-flex h-11 items-center gap-2 rounded-xl bg-white/10 px-4 text-xs font-black text-white hover:bg-white/20 disabled:cursor-wait disabled:opacity-60"><x-heroicon-o-hand-raised class="h-5 w-5" /><span data-hand-label>@lang('teacher-live-session::app.raise_hand')</span></button>
        <div class="flex items-center gap-1 rounded-xl bg-white/10 p-1" data-reactions aria-label="@lang('teacher-live-session::app.reactions')">
            <button type="button" data-reaction="clap" class="grid h-9 w-9 place-items-center rounded-lg hover:bg-white/10" aria-label="@lang('teacher-live-session::app.reaction_clap')"><x-heroicon-o-hand-raised class="h-4 w-4" /></button>
            <button type="button" data-reaction="heart" class="grid h-9 w-9 place-items-center rounded-lg hover:bg-white/10" aria-label="@lang('teacher-live-session::app.reaction_heart')"><x-heroicon-o-heart class="h-4 w-4" /></button>
            <button type="button" data-reaction="celebrate" class="grid h-9 w-9 place-items-center rounded-lg hover:bg-white/10" aria-label="@lang('teacher-live-session::app.reaction_celebrate')"><x-heroicon-o-sparkles class="h-4 w-4" /></button>
            <button type="button" data-reaction="question" class="grid h-9 w-9 place-items-center rounded-lg hover:bg-white/10" aria-label="@lang('teacher-live-session::app.reaction_question')"><x-heroicon-o-question-mark-circle class="h-4 w-4" /></button>
        </div>@endif
    </div>
    @if($collaborationEnabled)<aside data-collaboration-panel class="absolute inset-y-0 right-0 z-20 hidden w-full max-w-sm flex-col border-l border-slate-200 bg-white text-slate-900 shadow-2xl">
        <div class="flex items-center justify-between border-b border-slate-100 p-4"><div><h2 class="text-sm font-black">@lang('teacher-live-session::app.room_collaboration')</h2><p class="text-xs font-semibold text-slate-500">@lang('teacher-live-session::app.room_collaboration_hint')</p></div><button type="button" data-close-collaboration class="grid h-9 w-9 place-items-center rounded-xl text-slate-500 hover:bg-slate-100"><x-heroicon-o-x-mark class="h-5 w-5" /></button></div>
        <div class="grid grid-cols-2 border-b border-slate-100 p-2"><button type="button" data-panel-tab="participants" class="rounded-lg bg-green-50 px-3 py-2 text-xs font-black text-green-700">@lang('teacher-live-session::app.participants')</button><button type="button" data-panel-tab="chat" class="rounded-lg px-3 py-2 text-xs font-black text-slate-500">@lang('teacher-live-session::app.room_chat')</button></div>
        <div data-panel-content="participants" class="min-h-0 flex-1 space-y-2 overflow-y-auto p-3"></div>
        <div data-panel-content="chat" class="hidden min-h-0 flex-1 flex-col"><div data-chat-messages class="min-h-0 flex-1 space-y-3 overflow-y-auto p-4"></div><form data-chat-form class="flex gap-2 border-t border-slate-100 p-3"><input data-chat-input maxlength="2000" required class="h-10 min-w-0 flex-1 rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-green-400" placeholder="@lang('teacher-live-session::app.chat_placeholder')"><button class="grid h-10 w-10 place-items-center rounded-xl bg-green-600 text-white" title="@lang('teacher-live-session::app.send_message')"><x-heroicon-o-paper-airplane class="h-4 w-4" /></button></form></div>
    </aside>@endif
    @if(filled($mediaConfig['teachingToolsSyncUrl'] ?? null))<aside data-teaching-tools-panel class="absolute inset-0 z-30 hidden flex-col bg-white text-slate-900">
        <div class="flex items-center justify-between border-b border-slate-100 px-5 py-3"><div><h2 class="text-sm font-black">@lang('teacher-live-session::app.teaching_tools')</h2><p class="text-xs font-semibold text-slate-500">@lang('teacher-live-session::app.teaching_tools_hint')</p></div><button type="button" data-close-teaching-tools class="grid h-9 w-9 place-items-center rounded-xl text-slate-500 hover:bg-slate-100"><x-heroicon-o-x-mark class="h-5 w-5" /></button></div>
        <div class="grid grid-cols-3 border-b border-slate-100 p-2" role="tablist"><button type="button" role="tab" aria-selected="true" data-tool-tab="whiteboard" class="rounded-lg bg-green-50 px-3 py-2 text-xs font-black text-green-700">@lang('teacher-live-session::app.whiteboard')</button><button type="button" role="tab" aria-selected="false" data-tool-tab="poll" class="rounded-lg bg-transparent px-3 py-2 text-xs font-black text-slate-500">@lang('teacher-live-session::app.quick_poll')</button><button type="button" role="tab" aria-selected="false" data-tool-tab="resources" class="rounded-lg bg-transparent px-3 py-2 text-xs font-black text-slate-500">@lang('teacher-live-session::app.resources')</button></div>
        <div data-tool-content="whiteboard" class="relative min-h-0 flex-1 bg-slate-100 p-3"><canvas data-whiteboard role="img" aria-label="@lang('teacher-live-session::app.whiteboard')" class="h-full w-full touch-none rounded-xl bg-white shadow-sm"></canvas><div class="absolute bottom-5 left-1/2 flex -translate-x-1/2 items-center gap-2 rounded-xl border border-slate-200 bg-white p-2 shadow-lg"><input data-board-color aria-label="@lang('teacher-live-session::app.board_color')" type="color" value="#16a34a" class="h-8 w-8"><input data-board-width aria-label="@lang('teacher-live-session::app.board_width')" type="range" min="1" max="12" value="3" class="w-24">@if($mediaConfig['canRecord'] ?? false)<button type="button" data-clear-board class="rounded-lg bg-red-50 px-3 py-2 text-xs font-black text-red-600">@lang('teacher-live-session::app.clear_board')</button>@endif</div></div>
        <div data-tool-content="poll" class="hidden min-h-0 flex-1 overflow-y-auto p-5"><div data-poll-view></div>@if($mediaConfig['canRecord'] ?? false)<form data-poll-form class="mt-5 space-y-3 rounded-2xl border border-slate-200 p-4"><input data-poll-question required maxlength="500" class="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm font-bold" placeholder="@lang('teacher-live-session::app.poll_question')"><input data-poll-option required maxlength="300" class="h-10 w-full rounded-xl border border-slate-200 px-3 text-sm" placeholder="@lang('teacher-live-session::app.option') 1"><input data-poll-option required maxlength="300" class="h-10 w-full rounded-xl border border-slate-200 px-3 text-sm" placeholder="@lang('teacher-live-session::app.option') 2"><button class="h-10 rounded-xl bg-green-600 px-4 text-xs font-black text-white">@lang('teacher-live-session::app.launch_poll')</button></form>@endif</div>
        <div data-tool-content="resources" class="hidden min-h-0 flex-1 overflow-y-auto p-5"><div data-resource-list class="space-y-2"></div>@if($mediaConfig['canRecord'] ?? false)<form data-resource-form class="mt-5 flex gap-2 rounded-2xl border border-dashed border-slate-300 p-4"><input data-resource-file type="file" required accept=".pdf,.ppt,.pptx,.doc,.docx,.xls,.xlsx,.png,.jpg,.jpeg,.webp" class="min-w-0 flex-1 text-xs"><button class="h-9 rounded-xl bg-green-600 px-4 text-xs font-black text-white">@lang('teacher-live-session::app.upload')</button></form>@endif</div>
    </aside>@endif
    @if(filled($mediaConfig['breakoutSyncUrl'] ?? null))<aside data-breakout-panel class="absolute inset-y-0 right-0 z-30 hidden w-full max-w-md flex-col border-l border-slate-200 bg-white text-slate-900 shadow-2xl">
        <div class="flex items-center justify-between border-b border-slate-100 p-4"><div><h2 class="text-sm font-black">@lang('teacher-live-session::app.breakout_rooms')</h2><p class="text-xs font-semibold text-slate-500">@lang('teacher-live-session::app.breakout_rooms_hint')</p></div><button type="button" data-close-breakouts class="grid h-9 w-9 place-items-center rounded-xl text-slate-500 hover:bg-slate-100"><x-heroicon-o-x-mark class="h-5 w-5" /></button></div>
        <div data-breakout-current class="border-b border-slate-100 bg-green-50 px-4 py-3 text-xs font-black text-green-800"></div>
        <div data-breakout-list class="min-h-0 flex-1 space-y-3 overflow-y-auto p-4"></div>
        @if($mediaConfig['canRecord'] ?? false)<form data-breakout-form class="space-y-3 border-t border-slate-100 p-4"><div class="grid grid-cols-2 gap-3"><label class="text-xs font-bold text-slate-600">@lang('teacher-live-session::app.room_count')<input data-breakout-count type="number" min="2" max="20" value="2" class="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3"></label><label class="text-xs font-bold text-slate-600">@lang('teacher-live-session::app.duration_minutes')<input data-breakout-duration type="number" min="5" max="180" value="15" class="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3"></label></div><label class="flex items-center gap-2 text-xs font-bold text-slate-700"><input data-breakout-auto type="checkbox" checked class="rounded border-slate-300 text-green-600">@lang('teacher-live-session::app.auto_assign')</label><div class="flex gap-2"><button class="h-10 flex-1 rounded-xl bg-green-600 px-3 text-xs font-black text-white">@lang('teacher-live-session::app.create_rooms')</button><button type="button" data-open-breakouts class="h-10 rounded-xl bg-slate-900 px-3 text-xs font-black text-white">@lang('teacher-live-session::app.open_rooms')</button><button type="button" data-close-all-breakouts class="h-10 rounded-xl bg-red-50 px-3 text-xs font-black text-red-600">@lang('teacher-live-session::app.close_rooms')</button></div></form>@endif
    </aside>@endif
    <div data-reaction-layer class="pointer-events-none absolute inset-0 z-10 overflow-hidden"></div>
</section>
