@extends('Mindigo-dashboard::layouts')

@section('title', __('teacher-course::admin-review.review_course', ['course' => $course->name]))
@section('styles')
    @vite(['packages/Mindigo/Dashboard/src/resources/css/app.css', 'packages/Mindigo/Dashboard/src/resources/js/app.js'])
@endsection

@section('content')
<div class="min-h-screen bg-slate-50">
    <header class="sticky top-0 z-10 flex items-center gap-4 border-b border-slate-200 bg-white/95 px-6 py-4 backdrop-blur">
        <a href="{{ route('admin.course-publication-reviews.index') }}" aria-label="@lang('teacher-course::admin-review.back')" class="grid h-9 w-9 shrink-0 place-items-center rounded-full border border-slate-200 text-slate-600 no-underline hover:bg-green-50"><x-heroicon-o-arrow-left class="h-4 w-4" /></a>
        <div class="min-w-0"><p class="text-[11px] font-black uppercase tracking-widest text-green-700">@lang('teacher-course::admin-review.area')</p><h1 class="truncate text-lg font-black text-slate-950">{{ $course->name }}</h1><p class="text-xs font-semibold text-slate-400">{{ $course->teacher->name }} · @lang('teacher-course::admin-review.detail_subtitle')</p></div>
    </header>

    <main class="grid gap-5 p-4 sm:p-6 xl:grid-cols-[minmax(0,1fr)_22rem]">
        <div class="min-w-0 space-y-5">
            <section class="overflow-hidden rounded-xl border border-slate-200 bg-white">
                <div class="grid md:grid-cols-[15rem_minmax(0,1fr)]">
                    <div class="aspect-video bg-slate-100 md:aspect-auto">@if($course->cover_image)<img src="{{ asset('storage/'.$course->cover_image) }}" alt="{{ $course->name }}" class="h-full w-full object-cover">@else<div class="grid h-full min-h-48 place-items-center"><x-heroicon-o-book-open class="h-10 w-10 text-slate-300" /></div>@endif</div>
                    <div class="p-5"><span class="rounded-full bg-amber-50 px-3 py-1 text-[10px] font-black uppercase text-amber-700">@lang('teacher-course::admin-review.pending')</span><h2 class="mt-4 text-xl font-black text-slate-950">{{ $course->name }}</h2><p class="mt-2 text-sm font-semibold leading-6 text-slate-500">{{ $course->description ?: __('teacher-course::catalog.no_description') }}</p><dl class="mt-4 grid grid-cols-3 border-t border-slate-100 pt-4 text-center"><div><dt class="text-[10px] font-black uppercase text-slate-400">@lang('teacher-course::catalog.chapters')</dt><dd class="font-black">{{ $course->chapters_count }}</dd></div><div><dt class="text-[10px] font-black uppercase text-slate-400">@lang('teacher-course::catalog.lessons')</dt><dd class="font-black">{{ $course->lessons_count }}</dd></div><div><dt class="text-[10px] font-black uppercase text-slate-400">@lang('teacher-course::catalog.duration')</dt><dd class="font-black">{{ $course->durationLabel() }}</dd></div></dl></div>
                </div>
            </section>

            <section class="overflow-hidden rounded-xl border border-slate-200 bg-white"><div class="border-b border-slate-100 px-5 py-4"><h2 class="font-black">@lang('teacher-course::catalog.curriculum')</h2></div><div class="divide-y divide-slate-100">@forelse($course->chapters as $chapter)<details class="px-5 py-4" @if($loop->first) open @endif><summary class="cursor-pointer font-black text-slate-800">{{ $chapter->name }} <span class="ml-2 text-xs text-slate-400">({{ $chapter->lessons->count() }})</span></summary><ol class="mt-3 space-y-2 border-t border-slate-100 pt-3">@foreach($chapter->lessons as $lesson)<li class="flex items-center gap-3 rounded-lg bg-slate-50 px-3 py-2 text-sm font-semibold text-slate-600"><x-heroicon-o-play-circle class="h-4 w-4 text-green-600" /><span class="flex-1">{{ $lesson->name }}</span>@if($lesson->is_preview)<span class="text-[10px] font-black text-green-700">@lang('teacher-course::catalog.preview')</span>@endif</li>@endforeach</ol></details>@empty<p class="p-10 text-center text-sm font-semibold text-slate-400">@lang('teacher-course::admin-review.no_curriculum')</p>@endforelse</div></section>

            <section class="overflow-hidden rounded-xl border border-slate-200 bg-white"><div class="border-b border-slate-100 px-5 py-4"><h2 class="font-black">@lang('teacher-course::admin-review.history')</h2></div><div class="divide-y divide-slate-100">@forelse($course->reviewHistory as $history)<article class="grid gap-2 px-5 py-4 sm:grid-cols-[10rem_minmax(0,1fr)_10rem]"><div><span class="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black uppercase text-slate-600">@lang('teacher-course::admin-review.statuses.'.$history->review_status)</span></div><div><p class="text-sm font-bold text-slate-700">{{ $history->review_note ?: '—' }}</p><p class="mt-1 text-xs text-slate-400">{{ $history->publication_state_before }} → {{ $history->publication_state_after }}</p></div><div class="text-xs font-semibold text-slate-500">{{ $history->reviewer?->name ?: $course->teacher->name }}<br>{{ ($history->reviewed_at ?? $history->created_at)?->format('d/m/Y H:i') }}</div></article>@empty<p class="p-10 text-center text-sm font-semibold text-slate-400">@lang('teacher-course::admin-review.no_history')</p>@endforelse</div></section>
        </div>

        <aside class="space-y-5">
            <section class="rounded-xl border border-slate-200 bg-white p-5"><h2 class="font-black">@lang('teacher-course::admin-review.course_information')</h2><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between gap-3"><dt class="text-slate-400">@lang('teacher-course::admin-review.teacher')</dt><dd class="text-right font-bold">{{ $course->teacher->name }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-400">@lang('teacher-course::app.subject_field')</dt><dd class="text-right font-bold">{{ $course->subject?->name ?: '—' }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-400">@lang('teacher-course::app.category_field')</dt><dd class="text-right font-bold">{{ $course->category?->name ?: '—' }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-400">@lang('teacher-course::admin-review.submitted_at')</dt><dd class="text-right font-bold">{{ $course->submitted_for_review_at?->format('d/m/Y H:i') }}</dd></div></dl><a href="{{ route('courses.show', $course->slug) }}" target="_blank" class="mt-5 inline-flex h-10 w-full items-center justify-center gap-2 rounded-lg border border-slate-200 text-sm font-black text-slate-700 no-underline"><x-heroicon-o-arrow-top-right-on-square class="h-4 w-4" />@lang('teacher-course::admin-review.full_preview')</a></section>

            @if($course->publication_status === \Mindigo\TeacherCourse\Models\Course::PUBLICATION_PENDING_REVIEW)
                <section class="rounded-xl border border-slate-200 bg-white p-5"><h2 class="font-black">@lang('teacher-course::admin-review.decision')</h2><form method="POST" action="{{ route('admin.course-publication-reviews.update', $course) }}" class="mt-4 space-y-3">@csrf @method('PATCH')<label class="block"><span class="mb-2 block text-xs font-black uppercase text-slate-500">@lang('teacher-course::admin-review.note')</span><textarea name="review_note" rows="4" maxlength="2000" placeholder="@lang('teacher-course::admin-review.note_placeholder')" class="w-full resize-none rounded-xl border border-slate-200 p-3 text-sm font-semibold outline-none focus:border-green-400">{{ old('review_note') }}</textarea>@error('review_note')<p class="mt-1 text-xs font-bold text-red-600">{{ $message }}</p>@enderror</label><div class="grid gap-2"><button name="action" value="approve" class="inline-flex h-11 items-center justify-center gap-2 rounded-lg bg-green-600 text-sm font-black text-white"><x-heroicon-o-check-circle class="h-4 w-4" />@lang('teacher-course::admin-review.approve')</button><button name="action" value="request_changes" class="inline-flex h-11 items-center justify-center gap-2 rounded-lg border border-amber-200 bg-amber-50 text-sm font-black text-amber-700"><x-heroicon-o-pencil-square class="h-4 w-4" />@lang('teacher-course::admin-review.request_changes')</button></div></form></section>
            @endif
        </aside>
    </main>
</div>
@endsection
