<?php

return [
    'score_combinations' => [
        'A00' => ['math', 'physics', 'chemistry'],
        'A01' => ['math', 'physics', 'english'],
        'A02' => ['math', 'physics', 'biology'],
        'A03' => ['math', 'physics', 'history'],
        'A04' => ['math', 'physics', 'geography'],
        'A05' => ['math', 'chemistry', 'history'],
        'A06' => ['math', 'chemistry', 'geography'],
        'A07' => ['math', 'history', 'geography'],
        'A08' => ['math', 'history', 'civic_education'],
        'A09' => ['math', 'geography', 'civic_education'],
        'A10' => ['math', 'physics', 'civic_education'],
        'A11' => ['math', 'chemistry', 'civic_education'],
        'A12' => ['math', 'natural_sciences', 'social_sciences'],
        'A14' => ['math', 'natural_sciences', 'geography'],
        'A15' => ['math', 'natural_sciences', 'civic_education'],
        'A16' => ['math', 'natural_sciences', 'literature'],
        'A17' => ['math', 'physics', 'social_sciences'],
        'A18' => ['math', 'chemistry', 'social_sciences'],
        'B00' => ['math', 'chemistry', 'biology'],
        'B01' => ['math', 'biology', 'history'],
        'B02' => ['math', 'biology', 'geography'],
        'B03' => ['math', 'biology', 'literature'],
        'B04' => ['math', 'biology', 'civic_education'],
        'B05' => ['math', 'biology', 'social_sciences'],
        'B08' => ['math', 'biology', 'english'],
        'C00' => ['literature', 'history', 'geography'],
        'C01' => ['literature', 'math', 'physics'],
        'C02' => ['literature', 'math', 'chemistry'],
        'C03' => ['literature', 'math', 'history'],
        'C04' => ['literature', 'math', 'geography'],
        'C05' => ['literature', 'physics', 'chemistry'],
        'C06' => ['literature', 'physics', 'biology'],
        'C07' => ['literature', 'physics', 'history'],
        'C08' => ['literature', 'chemistry', 'biology'],
        'C09' => ['literature', 'physics', 'geography'],
        'C10' => ['literature', 'chemistry', 'history'],
        'C12' => ['literature', 'biology', 'history'],
        'C13' => ['literature', 'biology', 'geography'],
        'C14' => ['literature', 'math', 'civic_education'],
        'C15' => ['literature', 'math', 'social_sciences'],
        'C16' => ['literature', 'physics', 'civic_education'],
        'C17' => ['literature', 'chemistry', 'civic_education'],
        'C19' => ['literature', 'history', 'civic_education'],
        'C20' => ['literature', 'geography', 'civic_education'],
        'D01' => ['math', 'literature', 'english'],
        'D02' => ['math', 'literature', 'russian'],
        'D03' => ['math', 'literature', 'french'],
        'D04' => ['math', 'literature', 'chinese'],
        'D05' => ['math', 'literature', 'german'],
        'D06' => ['math', 'literature', 'japanese'],
        'D07' => ['math', 'chemistry', 'english'],
        'D08' => ['math', 'biology', 'english'],
        'D09' => ['math', 'history', 'english'],
        'D10' => ['math', 'geography', 'english'],
        'D11' => ['literature', 'physics', 'english'],
        'D12' => ['literature', 'chemistry', 'english'],
        'D13' => ['literature', 'biology', 'english'],
        'D14' => ['literature', 'history', 'english'],
        'D15' => ['literature', 'geography', 'english'],
        'D66' => ['literature', 'civic_education', 'english'],
        'D78' => ['literature', 'social_sciences', 'english'],
        'D84' => ['math', 'civic_education', 'english'],
        'D90' => ['math', 'natural_sciences', 'english'],
        'D96' => ['math', 'social_sciences', 'english'],
        'H00' => ['literature', 'art_drawing_1', 'art_drawing_2'],
        'H01' => ['math', 'literature', 'drawing'],
        'H02' => ['math', 'art_drawing_1', 'art_drawing_2'],
        'H03' => ['math', 'natural_sciences', 'drawing'],
        'H04' => ['math', 'english', 'drawing'],
        'H05' => ['literature', 'social_sciences', 'drawing'],
        'H06' => ['literature', 'english', 'drawing'],
        'K01' => ['math', 'english', 'informatics'],
        'M00' => ['literature', 'math', 'expressive_reading_singing'],
        'M01' => ['literature', 'history', 'aptitude'],
        'M02' => ['math', 'expressive_reading_singing', 'storytelling'],
        'M03' => ['literature', 'aptitude_1', 'aptitude_2'],
        'M05' => ['literature', 'history', 'aptitude'],
        'M06' => ['literature', 'math', 'aptitude'],
        'N00' => ['literature', 'music_aptitude_1', 'music_aptitude_2'],
        'N01' => ['literature', 'xam_singing', 'instrument'],
        'N02' => ['literature', 'vocal', 'sight_singing'],
        'N03' => ['literature', 'sight_singing', 'instrument'],
        'N04' => ['literature', 'presentation', 'aptitude'],
        'R00' => ['literature', 'history', 'journalism_aptitude'],
        'R01' => ['literature', 'geography', 'artistic_expression'],
        'R02' => ['literature', 'math', 'artistic_expression'],
        'R03' => ['literature', 'english', 'artistic_expression'],
        'R05' => ['literature', 'english', 'journalism_aptitude'],
        'S00' => ['literature', 'theatre_aptitude_1', 'theatre_aptitude_2'],
        'S01' => ['math', 'theatre_aptitude_1', 'theatre_aptitude_2'],
        'T00' => ['math', 'biology', 'sports_aptitude'],
        'T01' => ['math', 'literature', 'sports_aptitude'],
        'T02' => ['literature', 'biology', 'sports_aptitude'],
        'T03' => ['literature', 'geography', 'sports_aptitude'],
        'T04' => ['math', 'physics', 'sports_aptitude'],
        'T05' => ['literature', 'civic_education', 'sports_aptitude'],
        'T08' => ['math', 'civic_education', 'sports_aptitude'],
        'V00' => ['math', 'physics', 'drawing'],
        'V01' => ['math', 'literature', 'drawing'],
        'V02' => ['math', 'english', 'drawing'],
        'V03' => ['math', 'chemistry', 'drawing'],
        'V05' => ['literature', 'physics', 'drawing'],
        'V06' => ['math', 'geography', 'drawing'],
        'V10' => ['math', 'french', 'drawing'],
        'V11' => ['math', 'chinese', 'drawing'],
    ],
    'gpa' => [
        'grade_scale' => [
            ['min' => 8.5, 'letter' => 'A', 'points' => 4.0],
            ['min' => 7.0, 'letter' => 'B', 'points' => 3.0],
            ['min' => 5.5, 'letter' => 'C', 'points' => 2.0],
            ['min' => 4.0, 'letter' => 'D', 'points' => 1.0],
            ['min' => 0.0, 'letter' => 'F', 'points' => 0.0],
        ],
        'classifications' => ['excellent' => 3.6, 'very_good' => 3.2, 'good' => 2.5, 'average' => 2.0, 'insufficient' => 0.0],
    ],
    'categories' => [
        'all' => 'all',
        'memory' => 'memory',
        'practice' => 'practice',
        'planning' => 'planning',
        'orientation' => 'orientation',
    ],
    'tools' => [
        'pomodoro' => ['category' => 'planning', 'icon' => 'heroicon-o-clock', 'roles' => ['student', 'teacher'], 'status' => 'active', 'route' => 'learning-tools.pomodoro.index'],
        'notes' => ['category' => 'memory', 'icon' => 'heroicon-o-book-open', 'roles' => ['student', 'teacher'], 'status' => 'active', 'route' => 'learning-tools.notes.index'],
        'knowledge_base' => ['category' => 'memory', 'icon' => 'heroicon-o-light-bulb', 'roles' => ['student', 'teacher'], 'status' => 'active', 'route' => 'learning-tools.resources.index'],
        'flashcards' => ['category' => 'memory', 'icon' => 'heroicon-o-rectangle-stack', 'roles' => ['student', 'teacher'], 'status' => 'active', 'route' => 'learning-tools.flashcards.index'],
        'study_plan' => ['category' => 'planning', 'icon' => 'heroicon-o-calendar-days', 'roles' => ['student', 'teacher'], 'status' => 'active', 'route' => 'learning-tools.plans.index'],
        'mistake_notebook' => ['category' => 'practice', 'icon' => 'heroicon-o-exclamation-triangle', 'roles' => ['student', 'teacher'], 'status' => 'active', 'route' => 'learning-tools.mistakes.index'],
        'personalized_practice' => ['category' => 'practice', 'icon' => 'heroicon-o-pencil-square', 'roles' => ['student', 'teacher'], 'status' => 'active', 'route' => 'learning-tools.personalized.index'],
        'knowledge_gaps' => ['category' => 'practice', 'icon' => 'heroicon-o-chart-bar', 'roles' => ['student', 'teacher'], 'status' => 'active', 'route' => 'learning-tools.gaps.index'],
        'score_calculator' => ['category' => 'orientation', 'icon' => 'heroicon-o-calculator', 'roles' => ['student', 'teacher'], 'status' => 'active', 'route' => 'learning-tools.scores.index'],
        'admission_lookup' => ['category' => 'orientation', 'icon' => 'heroicon-o-magnifying-glass', 'roles' => ['student', 'teacher'], 'status' => 'active', 'route' => 'learning-tools.admissions.index'],
        'ai_tutor' => ['category' => 'practice', 'icon' => 'heroicon-o-sparkles', 'roles' => ['student', 'teacher'], 'status' => 'planned'],
    ],
];
