@extends('Mindigo-dashboard::layouts')

@section('title', ($skill ? __('student-practice::app.skills.edit') : __('student-practice::app.skills.create')).' - Mindigo LMS')
@section('styles')
    @vite(['packages/Mindigo/Dashboard/src/resources/css/app.css', 'packages/Mindigo/Dashboard/src/resources/js/app.js'])
@endsection

@section('content')
<div class="min-h-screen bg-slate-50"><header class="border-b border-slate-200 bg-white px-6 py-4"><a href="{{ route('practice.skills.index') }}" class="text-xs font-black text-green-700 no-underline">← @lang('student-practice::app.back')</a><h1 class="mt-2 text-lg font-black text-slate-950">{{ $skill ? __('student-practice::app.skills.edit') : __('student-practice::app.skills.create') }}</h1></header>
<main class="mx-auto max-w-5xl p-6"><form method="POST" action="{{ $skill ? route('practice.skills.update', $skill) : route('practice.skills.store') }}" class="rounded-xl border border-slate-200 bg-white p-6">@csrf @if($skill)@method('PUT')@endif
    @if($errors->any())<div class="mb-5 border border-red-200 bg-red-50 px-4 py-3 text-sm font-bold text-red-700">{{ $errors->first() }}</div>@endif
    <div class="grid gap-5 md:grid-cols-2">
        <label><span class="mb-1.5 block text-xs font-black text-slate-600">@lang('student-practice::app.subject')</span><select name="subject_id" required class="h-11 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm font-semibold">@foreach($subjects as $subject)<option value="{{ $subject->id }}" @selected((string) old('subject_id', $skill?->subject_id) === (string) $subject->id)>{{ $subject->name }}</option>@endforeach</select></label>
        <label><span class="mb-1.5 block text-xs font-black text-slate-600">@lang('student-practice::app.topic')</span><select name="subject_topic_id" class="h-11 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm font-semibold"><option value="">@lang('student-practice::app.all')</option>@foreach($subjects as $subject)@foreach($subject->topics as $topic)<option value="{{ $topic->id }}" @selected((string) old('subject_topic_id', $skill?->subject_topic_id) === (string) $topic->id)>{{ $subject->name }} · {{ $topic->name }}</option>@endforeach @endforeach</select></label>
        <label><span class="mb-1.5 block text-xs font-black text-slate-600">@lang('student-practice::app.skills.code')</span><input name="code" required value="{{ old('code', $skill?->code) }}" class="h-11 w-full rounded-lg border border-slate-300 px-3 text-sm font-semibold"></label>
        <label><span class="mb-1.5 block text-xs font-black text-slate-600">@lang('student-practice::app.skills.name')</span><input name="name" required value="{{ old('name', $skill?->name) }}" class="h-11 w-full rounded-lg border border-slate-300 px-3 text-sm font-semibold"></label>
        <label><span class="mb-1.5 block text-xs font-black text-slate-600">@lang('student-practice::app.skills.grade_level')</span><input name="grade_level" value="{{ old('grade_level', $skill?->grade_level) }}" class="h-11 w-full rounded-lg border border-slate-300 px-3 text-sm font-semibold"></label>
        <label><span class="mb-1.5 block text-xs font-black text-slate-600">@lang('student-practice::app.skills.parent')</span><select name="parent_id" class="h-11 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm font-semibold"><option value="">@lang('student-practice::app.skills.no_parent')</option>@foreach($parents as $parent)<option value="{{ $parent->id }}" @selected((string) old('parent_id', $skill?->parent_id) === (string) $parent->id)>{{ $parent->code }} · {{ $parent->name }}</option>@endforeach</select></label>
        <label><span class="mb-1.5 block text-xs font-black text-slate-600">@lang('student-practice::app.skills.status')</span><select name="status" class="h-11 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm font-semibold">@foreach($statuses as $status)<option value="{{ $status }}" @selected(old('status', $skill?->status ?? 'active') === $status)>@lang('student-practice::app.skills.statuses.'.$status)</option>@endforeach</select></label>
        <label><span class="mb-1.5 block text-xs font-black text-slate-600">@lang('student-practice::app.skills.sort_order')</span><input type="number" min="0" name="sort_order" value="{{ old('sort_order', $skill?->sort_order ?? 0) }}" class="h-11 w-full rounded-lg border border-slate-300 px-3 text-sm font-semibold"></label>
        <label class="md:col-span-2"><span class="mb-1.5 block text-xs font-black text-slate-600">@lang('student-practice::app.skills.description')</span><textarea name="description" rows="3" class="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold">{{ old('description', $skill?->description) }}</textarea></label>
    </div>
    <section class="mt-7 border-t border-slate-200 pt-6"><h2 class="text-sm font-black text-slate-900">@lang('student-practice::app.skills.assign_questions')</h2><p class="mt-1 text-xs font-semibold text-slate-400">@lang('student-practice::app.skills.assign_questions_hint')</p><div class="mt-4 max-h-80 overflow-y-auto rounded-lg border border-slate-200 divide-y divide-slate-100">@forelse($questions as $question)<label class="flex cursor-pointer items-start gap-3 px-4 py-3 hover:bg-slate-50"><input type="checkbox" name="question_ids[]" value="{{ $question->id }}" class="mt-1" @checked(in_array($question->id, old('question_ids', $skill?->questions?->pluck('id')->all() ?? [])))><span><strong class="block text-sm font-bold text-slate-800">{{ strip_tags($question->content) }}</strong><span class="text-xs font-semibold text-slate-400">{{ $question->subject }} · {{ $question->topic }} · {{ __('student-practice::app.difficulties.'.$question->difficulty) }}</span></span></label>@empty<p class="p-5 text-sm font-semibold text-slate-400">@lang('student-practice::app.no_questions')</p>@endforelse</div></section>
    <div class="mt-6 flex justify-end gap-3"><a href="{{ route('practice.skills.index') }}" class="rounded-lg border border-slate-300 px-5 py-2.5 text-sm font-black text-slate-700 no-underline">@lang('student-practice::app.back')</a><button class="rounded-lg bg-green-600 px-5 py-2.5 text-sm font-black text-white hover:bg-green-700">@lang('student-practice::app.skills.save')</button></div>
</form></main></div>
@endsection
