@extends('Mindigo-dashboard::layouts')
@section('title', __('student-practice::app.analytics.title').' - Mindigo LMS')
@section('styles')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.min.js"></script>
    @vite(['packages/Mindigo/Dashboard/src/resources/css/app.css', 'packages/Mindigo/Dashboard/src/resources/js/app.js'])
@endsection
@section('content')
<div class="min-h-screen bg-slate-50">
    <header class="border-b border-slate-200 bg-white px-6 py-4"><div class="flex flex-wrap items-center justify-between gap-4"><div><p class="text-[11px] font-black uppercase tracking-widest text-green-700">@lang('student-practice::app.area')</p><h1 class="mt-0.5 text-lg font-black text-slate-950">@lang('student-practice::app.analytics.title')</h1><p class="text-xs font-semibold text-slate-400">@lang('student-practice::app.analytics.subtitle')</p></div><div class="flex items-center gap-2"><form method="GET" class="flex gap-2"><select name="period" data-mindigo-auto-submit class="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm font-bold text-slate-700 outline-none focus:border-green-300">@foreach(['7','30','90','all'] as $value)<option value="{{ $value }}" @selected(request('period', config('practice.analytics.default_period')) === $value)>@lang('student-practice::app.analytics.periods.'.$value)</option>@endforeach</select><select name="skill_id" data-mindigo-auto-submit class="h-10 max-w-52 rounded-xl border border-slate-200 bg-white px-3 text-sm font-bold text-slate-700 outline-none focus:border-green-300"><option value="">@lang('student-practice::app.analytics.all_skills')</option>@foreach($skillOptions as $option)<option value="{{ $option->id }}" @selected((string) request('skill_id') === (string) $option->id)>{{ $option->name }}</option>@endforeach</select></form><a href="{{ route('student.practice.index') }}" aria-label="@lang('student-practice::app.back')" class="grid h-10 w-10 place-items-center rounded-full border border-slate-200 bg-white text-slate-600 no-underline hover:text-green-700"><x-heroicon-o-arrow-left class="h-5 w-5" /></a></div></div></header>
    <main class="space-y-5 p-6">
        <section class="grid overflow-hidden rounded-xl border border-slate-200 bg-white sm:grid-cols-3 xl:grid-cols-6">@foreach([['attempts',$overview['attempts']],['questions',$overview['questions']],['accuracy',number_format($overview['accuracy'],1).'%'],['average_score',number_format($overview['average_score'],1)],['practice_time',__('student-practice::app.analytics.minutes',['count'=>round($overview['practice_seconds']/60)])],['improvement',($improvement['change'] > 0 ? '+' : '').number_format($improvement['change'],1)]] as [$label,$value])<div class="border-b border-slate-100 p-4 last:border-0 sm:border-r xl:border-b-0"><strong class="block text-2xl font-black text-slate-950">{{ $value }}</strong><span class="text-[11px] font-bold text-slate-400">@lang('student-practice::app.analytics.'.$label)</span></div>@endforeach</section>
        <section class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_22rem]">
            <article class="rounded-xl border border-slate-200 bg-white p-5"><div class="mb-4"><h2 class="text-base font-black text-slate-950">@lang('student-practice::app.analytics.trend_title')</h2><p class="text-xs font-semibold text-slate-400">@lang('student-practice::app.analytics.trend_subtitle')</p></div><div class="h-64"><canvas id="practiceAnalyticsTrend"></canvas></div></article>
            <aside class="overflow-hidden rounded-xl border border-slate-200 bg-white"><div class="border-b border-slate-100 px-5 py-4"><h2 class="text-base font-black text-slate-950">@lang('student-practice::app.analytics.insights')</h2><p class="text-xs font-semibold text-slate-400">@lang('student-practice::app.analytics.insights_hint')</p></div><div class="divide-y divide-slate-100">@forelse($insights as $insight)<div class="px-5 py-4"><div class="flex items-center justify-between gap-2"><strong class="text-sm text-slate-800">@lang('student-practice::app.analytics.insight_types.'.$insight->type)</strong>@if($insight->skill)<span class="rounded-full bg-green-50 px-2 py-1 text-[10px] font-black text-green-700">{{ $insight->skill->name }}</span>@endif</div><p class="mt-1 text-xs font-semibold leading-relaxed text-slate-400">{{ __('student-practice::app.analytics.insight_codes.'.$insight->insight_code, $insight->metrics) }}</p></div>@empty<p class="px-5 py-12 text-center text-sm font-semibold text-slate-400">@lang('student-practice::app.analytics.no_insights')</p>@endforelse</div></aside>
        </section>
        <section class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_22rem]">
            <article class="overflow-hidden rounded-xl border border-slate-200 bg-white"><div class="border-b border-slate-100 px-5 py-4"><h2 class="text-base font-black text-slate-950">@lang('student-practice::app.analytics.by_skill')</h2></div>@forelse($skills as $skill)<a href="{{ route('student.practice.skills.show', $skill['id']) }}" class="grid gap-3 border-b border-slate-100 px-5 py-4 text-slate-700 no-underline last:border-0 hover:bg-slate-50 md:grid-cols-[minmax(0,1fr)_7rem_7rem_7rem_2rem] md:items-center"><div><span class="text-[10px] font-black uppercase tracking-wider text-green-700">{{ $skill['subject'] }}</span><strong class="mt-1 block text-sm text-slate-950">{{ $skill['name'] }}</strong></div><div><strong class="block text-sm">{{ number_format($skill['mastery_score'],1) }}%</strong><span class="text-[10px] font-bold text-slate-400">@lang('student-practice::app.analytics.mastery')</span></div><div><strong class="block text-sm">{{ number_format($skill['accuracy'],1) }}%</strong><span class="text-[10px] font-bold text-slate-400">@lang('student-practice::app.accuracy')</span></div><div><strong class="block text-sm">{{ $skill['attempts'] }}</strong><span class="text-[10px] font-bold text-slate-400">@lang('student-practice::app.attempts')</span></div><x-heroicon-o-chevron-right class="h-5 w-5 text-slate-400" /></a>@empty<p class="px-5 py-12 text-center text-sm font-semibold text-slate-400">@lang('student-practice::app.analytics.no_data')</p>@endforelse</article>
            <aside class="overflow-hidden rounded-xl border border-slate-200 bg-white"><div class="border-b border-slate-100 px-5 py-4"><h2 class="text-base font-black text-slate-950">@lang('student-practice::app.analytics.next_skills')</h2></div>@forelse($recommendations->take(5) as $recommendation)<a href="{{ route('student.practice.skills.show', $recommendation->skill) }}" class="block border-b border-slate-100 px-5 py-4 text-slate-700 no-underline last:border-0 hover:bg-slate-50"><strong class="block text-sm">{{ $recommendation->skill->name }}</strong><span class="mt-1 block text-xs font-semibold text-slate-400">{{ __('student-practice::app.adaptive.reasons.'.$recommendation->reason_code) }}</span></a>@empty<p class="px-5 py-12 text-center text-sm font-semibold text-slate-400">@lang('student-practice::app.analytics.no_recommendations')</p>@endforelse</aside>
        </section>
        <section class="overflow-hidden rounded-xl border border-slate-200 bg-white"><div class="border-b border-slate-100 px-5 py-4"><h2 class="text-base font-black text-slate-950">@lang('student-practice::app.analytics.recent_history')</h2></div>@forelse($history as $attempt)<a href="{{ route('student.practice.result', $attempt) }}" class="grid grid-cols-2 gap-3 border-b border-slate-100 px-5 py-4 text-sm text-slate-700 no-underline last:border-0 hover:bg-slate-50 md:grid-cols-[minmax(0,1fr)_8rem_8rem_10rem]"><strong>{{ $attempt->practiceSkill?->name }}</strong><span>{{ $attempt->correct_answers }}/{{ $attempt->total_questions }}</span><span class="font-black text-green-700">{{ number_format($attempt->score,1) }}</span><span class="text-right text-xs font-semibold text-slate-400">{{ $attempt->completed_at?->format('d/m/Y H:i') }}</span></a>@empty<p class="px-5 py-12 text-center text-sm font-semibold text-slate-400">@lang('student-practice::app.analytics.no_data')</p>@endforelse<div class="px-5 py-3">{{ $history->links() }}</div></section>
    </main>
</div>
@endsection
@section('scripts')
<script>
document.addEventListener('DOMContentLoaded', function () {
    if (typeof Chart === 'undefined') return;
    const element = document.getElementById('practiceAnalyticsTrend');
    if (!element) return;
    new Chart(element, {type: 'line', data: {labels: {{ Illuminate\Support\Js::from($trend->pluck('practice_date')) }}, datasets: [{data: {{ Illuminate\Support\Js::from($trend->pluck('average_score')->map(fn ($score) => round($score, 2))) }}, borderColor: '#16a34a', backgroundColor: 'rgba(22,163,74,.10)', fill: true, tension: .3, pointRadius: 3}]}, options: {responsive: true, maintainAspectRatio: false, plugins: {legend: {display: false}}, scales: {y: {beginAtZero: true, max: 100, grid: {color: '#f1f5f9'}}, x: {grid: {display: false}}}}});
});
</script>
@endsection
