@extends('Mindigo-dashboard::layouts')

@section('title', $skill->name.' - Auronsoft LMS')
@section('styles')
    @vite(['packages/Mindigo/Dashboard/src/resources/css/app.css', 'packages/Mindigo/Dashboard/src/resources/js/app.js'])
@endsection

@section('content')
<div class="min-h-screen bg-slate-50">
    <header class="border-b border-slate-200 bg-white px-6 py-4"><div class="flex items-center justify-between gap-4"><div><p class="text-[11px] font-black uppercase tracking-widest text-green-700">{{ $skill->subject->name }}{{ $skill->grade_level ? ' · '.$skill->grade_level : '' }}</p><h1 class="mt-0.5 text-lg font-black text-slate-950">{{ $skill->name }}</h1><p class="text-xs font-semibold text-slate-400">{{ $skill->description ?: __('student-practice::app.skill_practice.no_description') }}</p></div><a href="{{ route('student.practice.skills.index') }}" aria-label="@lang('student-practice::app.back')" class="grid h-10 w-10 place-items-center rounded-full border border-slate-200 bg-white text-slate-600 no-underline hover:text-green-700"><x-heroicon-o-arrow-left class="h-5 w-5" /></a></div></header>
    <main class="grid gap-6 p-6 xl:grid-cols-[minmax(0,1fr)_20rem]">
        <section class="space-y-5">
            <div class="grid overflow-hidden rounded-xl border border-slate-200 bg-white sm:grid-cols-4">
                @foreach([['questions_count', $skill->questions_count], ['completed_attempts', $progress?->completed_attempts ?? 0], ['accuracy', number_format($progress?->accuracy ?? 0, 1).'%'], ['best_score', number_format($progress?->best_score ?? 0, 1)]] as [$label, $value])<div class="border-b border-slate-100 p-5 last:border-0 sm:border-b-0 sm:border-r"><strong class="block text-2xl font-black text-slate-950">{{ $value }}</strong><span class="text-xs font-bold text-slate-400">@lang('student-practice::app.skill_practice.'.$label)</span></div>@endforeach
            </div>
            <div class="overflow-hidden rounded-xl border border-slate-200 bg-white"><div class="border-b border-slate-100 px-5 py-4"><h2 class="font-black text-slate-950">@lang('student-practice::app.skill_practice.recent')</h2></div>@forelse($history as $attempt)<a href="{{ route('student.practice.result', $attempt) }}" class="grid grid-cols-3 gap-3 border-b border-slate-100 px-5 py-4 text-sm no-underline last:border-0 hover:bg-slate-50"><span class="font-bold text-slate-700">{{ $attempt->completed_at?->format('d/m/Y H:i') }}</span><span class="text-center font-semibold text-slate-500">{{ $attempt->correct_answers }}/{{ $attempt->total_questions }}</span><strong class="text-right text-green-700">{{ number_format($attempt->score, 1) }}</strong></a>@empty<p class="px-5 py-12 text-center text-sm font-semibold text-slate-400">@lang('student-practice::app.skill_practice.no_history')</p>@endforelse</div>
            {{ $history->links() }}
        </section>
        <aside class="self-start rounded-xl border border-slate-200 bg-white p-5"><h2 class="text-base font-black text-slate-950">@lang('student-practice::app.skill_practice.start_title')</h2><p class="mt-1 text-xs font-semibold text-slate-400">@lang('student-practice::app.skill_practice.start_hint')</p>@if($errors->any())<p class="mt-3 text-xs font-bold text-red-600">{{ $errors->first() }}</p>@endif<form action="{{ route('student.practice.skills.start', $skill) }}" method="POST" class="mt-5 space-y-4">@csrf<label class="block"><span class="mb-1.5 block text-xs font-bold text-slate-600">@lang('student-practice::app.difficulty')</span><select name="difficulty" class="h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm font-semibold"><option value="">@lang('student-practice::app.all')</option>@foreach(\Mindigo\QuestionBank\Models\Question::DIFFICULTIES as $difficulty)<option value="{{ $difficulty }}">{{ __('student-practice::app.difficulties.'.$difficulty) }} ({{ $difficultyCounts[$difficulty] ?? 0 }})</option>@endforeach</select></label><label class="block"><span class="mb-1.5 block text-xs font-bold text-slate-600">@lang('student-practice::app.question_count')</span><input type="number" name="question_count" value="{{ old('question_count', 10) }}" min="1" max="50" class="h-10 w-full rounded-lg border border-slate-300 px-3 text-sm font-semibold"></label><button @disabled($skill->questions_count === 0) class="w-full rounded-lg bg-green-600 px-4 py-2.5 text-sm font-black text-white hover:bg-green-700 disabled:cursor-not-allowed disabled:bg-slate-300">@lang('student-practice::app.start')</button></form></aside>
    </main>
</div>
@endsection
