@extends('Mindigo-dashboard::layouts')
@section('title', __('learning-tools::app.gpa.title') . ' · Mindigo LMS')
@section('styles') @vite(['packages/Mindigo/Dashboard/src/resources/css/app.css', 'packages/Mindigo/Dashboard/src/resources/js/app.js']) @endsection
@section('content')
<div class="flex min-h-screen flex-col bg-slate-50">@include('learning-tools::partials.header', ['eyebrow' => __('learning-tools::app.eyebrow'), 'title' => __('learning-tools::app.gpa.title'), 'subtitle' => __('learning-tools::app.gpa.subtitle'), 'actionRoute' => route('learning-tools.academic.index'), 'actionLabel' => __('learning-tools::app.academic.open')])<main class="p-6">
<form method="POST" action="{{ route('learning-tools.gpa.store') }}" class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">@csrf<label class="block max-w-xl text-sm font-black text-slate-700">@lang('learning-tools::app.gpa.scenario_name')<input name="title" value="{{ old('title') }}" required class="mt-2 h-11 w-full rounded-xl border border-slate-200 px-4 font-semibold"></label><p class="mt-3 text-xs font-semibold text-slate-400">@lang('learning-tools::app.gpa.weight_help')</p>
<div class="mt-5 space-y-4">@for($course = 0; $course < 8; $course++)<section class="rounded-2xl border border-slate-200 p-4"><div class="grid gap-3 sm:grid-cols-[1fr_100px_120px]"><input name="courses[{{ $course }}][name]" value="{{ old('courses.'.$course.'.name') }}" placeholder="{{ __('learning-tools::app.gpa.course_name') }}" class="h-10 rounded-xl border border-slate-200 px-3 text-sm font-semibold"><input type="number" name="courses[{{ $course }}][credits]" value="{{ old('courses.'.$course.'.credits') }}" min="1" max="20" placeholder="{{ __('learning-tools::app.gpa.credits') }}" class="h-10 rounded-xl border border-slate-200 px-3 text-sm font-semibold"><input type="number" name="courses[{{ $course }}][score]" value="{{ old('courses.'.$course.'.score') }}" min="0" max="10" step="0.01" placeholder="{{ __('learning-tools::app.gpa.final_score') }}" class="h-10 rounded-xl border border-slate-200 px-3 text-sm font-semibold"></div>
<details class="mt-3"><summary class="cursor-pointer text-xs font-black text-green-700">@lang('learning-tools::app.gpa.custom_formula')</summary><div class="mt-3 grid gap-2">@for($component = 0; $component < 5; $component++)<div class="grid grid-cols-[1fr_100px_100px] gap-2"><input name="courses[{{ $course }}][components][{{ $component }}][name]" value="{{ old('courses.'.$course.'.components.'.$component.'.name') }}" placeholder="{{ __('learning-tools::app.gpa.component') }}" class="h-9 rounded-lg border border-slate-200 px-3 text-xs font-semibold"><input type="number" name="courses[{{ $course }}][components][{{ $component }}][score]" value="{{ old('courses.'.$course.'.components.'.$component.'.score') }}" min="0" max="10" step="0.01" placeholder="{{ __('learning-tools::app.gpa.score') }}" class="h-9 rounded-lg border border-slate-200 px-2 text-xs font-semibold"><input type="number" name="courses[{{ $course }}][components][{{ $component }}][weight]" value="{{ old('courses.'.$course.'.components.'.$component.'.weight') }}" min="0.01" max="100" step="0.01" placeholder="{{ __('learning-tools::app.gpa.weight') }}" class="h-9 rounded-lg border border-slate-200 px-2 text-xs font-semibold"></div>@endfor</div></details></section>@endfor</div>
@if($errors->any())<p class="mt-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{{ $errors->first() }}</p>@endif<div class="mt-5 flex justify-end"><button class="rounded-full bg-green-600 px-7 py-3 text-sm font-black text-white">@lang('learning-tools::app.gpa.calculate_save')</button></div></form>
<section class="mt-6 grid gap-4 xl:grid-cols-2">@forelse($scenarios as $scenario)<article class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between"><div><h2 class="font-black text-slate-900">{{ $scenario->title }}</h2><p class="mt-1 text-xs font-bold text-slate-400">{{ trans_choice('learning-tools::app.gpa.credit_count', $scenario->total_credits, ['count' => $scenario->total_credits]) }}</p></div><form method="POST" action="{{ route('learning-tools.gpa.destroy', $scenario) }}">@csrf @method('DELETE')<button class="text-red-500"><x-heroicon-o-trash class="h-5 w-5" /></button></form></div><div class="mt-4 grid grid-cols-3 gap-3 text-center"><div class="rounded-2xl bg-slate-50 p-3"><p class="text-[10px] font-black uppercase text-slate-400">@lang('learning-tools::app.gpa.scale_ten')</p><strong class="text-xl font-black text-slate-800">{{ number_format($scenario->average_ten, 2) }}</strong></div><div class="rounded-2xl bg-green-50 p-3"><p class="text-[10px] font-black uppercase text-green-600">GPA 4.0</p><strong class="text-xl font-black text-green-700">{{ number_format($scenario->gpa_four, 2) }}</strong></div><div class="rounded-2xl bg-amber-50 p-3"><p class="text-[10px] font-black uppercase text-amber-600">@lang('learning-tools::app.gpa.classification')</p><strong class="text-sm font-black text-amber-700">@lang('learning-tools::app.gpa.classifications.' . $scenario->classification)</strong></div></div><div class="mt-4 space-y-2">@foreach($scenario->courses as $course)<div class="flex justify-between text-xs font-bold text-slate-500"><span>{{ $course['name'] }} · {{ $course['credits'] }} TC</span><span>{{ number_format($course['score'], 2) }} · {{ $course['letter'] }} · {{ $course['points'] }}</span></div>@endforeach</div></article>@empty<div class="col-span-full rounded-3xl border border-dashed border-slate-300 bg-white py-16 text-center"><p class="font-black text-slate-600">@lang('learning-tools::app.gpa.empty')</p></div>@endforelse</section><p class="mt-4 text-xs font-semibold text-slate-400">@lang('learning-tools::app.gpa.disclaimer')</p></main></div>
@endsection
