@extends('Mindigo-dashboard::layouts')
@section('title', __('Mindigo-exam-management::app.cutover.title'))
@section('styles') @vite(['packages/Mindigo/Dashboard/src/resources/css/app.css', 'packages/Mindigo/ExamManagement/src/resources/css/app.css']) @endsection
@section('content')
<main class="exam-foundation-shell"><div class="exam-foundation-container space-y-5">
<x-exam::page-header :eyebrow="__('Mindigo-exam-management::app.cutover.workspace')" :title="__('Mindigo-exam-management::app.cutover.title')" :description="__('Mindigo-exam-management::app.cutover.description')" />
<section class="grid gap-4 lg:grid-cols-2">
<x-exam::panel :title="__('Mindigo-exam-management::app.cutover.mode')"><form method="POST" action="{{ route('admin.exam-cutover.update') }}" class="space-y-4">@csrf @method('PUT')
<div class="grid gap-3 sm:grid-cols-2">@foreach(['parallel','new'] as $option)<label class="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 p-4 text-sm font-bold"><input type="radio" name="mode" value="{{ $option }}" @checked($mode === $option) class="text-green-600"><span>@lang('Mindigo-exam-management::app.cutover.'.$option)</span></label>@endforeach</div>
<div><p class="mb-2 text-sm font-black text-slate-700">@lang('Mindigo-exam-management::app.cutover.beta_teachers')</p><p class="mb-3 text-xs font-semibold text-slate-500">@lang('Mindigo-exam-management::app.cutover.beta_hint')</p><div class="max-h-48 space-y-2 overflow-y-auto">@foreach($teachers as $teacher)<label class="flex items-center gap-3 rounded-xl bg-slate-50 px-3 py-2 text-sm font-bold"><input type="checkbox" name="beta_teacher_ids[]" value="{{ $teacher->id }}" @checked(in_array($teacher->id, $betaTeacherIds, true)) class="rounded text-green-600"><span>{{ $teacher->name }} <small class="text-slate-400">{{ $teacher->email }}</small></span></label>@endforeach</div></div>
<label class="block text-sm font-black text-slate-700">@lang('Mindigo-exam-management::app.cutover.confirmation')<input name="confirmation" class="exam-input mt-2" placeholder="@lang('Mindigo-exam-management::app.cutover.cutover_confirmation')" required></label><x-exam::button type="submit">@lang('Mindigo-exam-management::app.cutover.save')</x-exam::button></form></x-exam::panel>
<x-exam::panel :title="__('Mindigo-exam-management::app.cutover.source_inventory')"><div class="grid grid-cols-2 gap-3">@foreach(['selected_exams','questions','attempts','answers','already_migrated'] as $key)<article class="exam-foundation-stat-card"><p class="exam-stat-label">@lang('Mindigo-exam-management::app.cutover.'.$key)</p><strong class="exam-stat-value">{{ number_format($preview[$key]) }}</strong></article>@endforeach</div><form method="POST" action="{{ route('admin.exam-cutover.migrate') }}" class="mt-5 space-y-3">@csrf<label class="block text-sm font-black text-slate-700">@lang('Mindigo-exam-management::app.cutover.confirmation')<input name="confirmation" class="exam-input mt-2" placeholder="@lang('Mindigo-exam-management::app.cutover.migration_confirmation')" required></label><x-exam::button type="submit" :disabled="$mode !== 'parallel'">@lang('Mindigo-exam-management::app.cutover.migrate')</x-exam::button></form></x-exam::panel>
</section>
<x-exam::panel :title="__('Mindigo-exam-management::app.cutover.comparison')"><div class="overflow-x-auto"><table class="exam-table"><thead><tr><th></th><th>@lang('Mindigo-exam-management::app.cutover.legacy')</th><th>@lang('Mindigo-exam-management::app.cutover.migrated')</th><th>@lang('Mindigo-exam-management::app.cutover.matches')</th></tr></thead><tbody>@foreach($comparison as $entity => $row)<tr><td class="font-black">{{ ucfirst($entity) }}</td><td>{{ $row['legacy'] }}</td><td>{{ $row['migrated'] }}</td><td>{{ $row['matches'] ? '✓' : '!' }}</td></tr>@endforeach</tbody></table></div></x-exam::panel>
<x-exam::panel :title="__('Mindigo-exam-management::app.cutover.runs')"><div class="overflow-x-auto"><table class="exam-table"><thead><tr><th>@lang('Mindigo-exam-management::app.cutover.run')</th><th>@lang('Mindigo-exam-management::app.cutover.status')</th><th>@lang('Mindigo-exam-management::app.cutover.initiator')</th><th>@lang('Mindigo-exam-management::app.cutover.started')</th></tr></thead><tbody>@forelse($runs as $run)<tr><td class="font-mono text-xs">{{ $run->uuid }}</td><td>{{ $run->status }}</td><td>{{ $run->initiator?->name ?? '—' }}</td><td>{{ $run->started_at?->format('d/m/Y H:i') }}</td></tr>@empty<tr><td colspan="4" class="text-center text-slate-400">@lang('Mindigo-exam-management::app.cutover.no_issues')</td></tr>@endforelse</tbody></table></div></x-exam::panel>
</div></main>
@endsection
