@extends('Mindigo-dashboard::layouts')
@section('title', __('teacher-course::reviews.title'))
@section('styles')
    @vite([
        'packages/Mindigo/Dashboard/src/resources/css/app.css',
        'packages/Mindigo/Dashboard/src/resources/js/app.js',
    ])
@endsection
@section('content')
<main class="min-h-screen bg-slate-50"><header class="border-b border-slate-200 bg-white px-6 py-4"><p class="text-[11px] font-black uppercase tracking-widest text-green-700">@lang('teacher-course::reviews.title')</p><h1 class="text-lg font-black text-slate-950">@lang('teacher-course::reviews.title')</h1><p class="text-xs font-semibold text-slate-400">@lang('teacher-course::reviews.summary', ['count' => $reviews->total()])</p></header><div class="p-6"><section class="overflow-hidden rounded-xl border border-slate-200 bg-white"><form method="GET" class="grid gap-3 border-b border-slate-200 p-4 sm:grid-cols-[minmax(0,1fr)_220px_auto]"><input name="search" value="{{ $filters['search'] ?? '' }}" placeholder="{{ __('teacher-course::reviews.comment_placeholder') }}" class="rounded-lg border border-slate-200 px-3 py-2 text-sm"><select name="status" class="rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="">@lang('teacher-course::publishing.all_statuses')</option>@foreach(\Mindigo\TeacherCourse\Models\CourseReview::MODERATION_STATUSES as $status)<option value="{{ $status }}" @selected(($filters['status'] ?? '') === $status)>@lang('teacher-course::reviews.statuses.'.$status)</option>@endforeach</select><button class="rounded-lg bg-green-600 px-4 text-xs font-black text-white">@lang('teacher-course::publishing.filter')</button></form><div class="divide-y divide-slate-100">@forelse($reviews as $review)<article class="grid gap-3 p-5 lg:grid-cols-[minmax(0,1fr)_300px]"><div><p class="font-black text-slate-900">{{ $review->course->name }} · {{ $review->student->name }}</p><p class="text-xs font-black text-amber-500">{{ str_repeat('★', $review->rating) }}</p><p class="mt-2 text-sm font-semibold text-slate-600">{{ $review->comment }}</p>@if($review->moderation_reason)<p class="mt-2 text-xs font-bold text-red-600">{{ $review->moderation_reason }}</p>@endif</div><form method="POST" action="{{ route('admin.course-reviews.moderate', $review) }}" class="flex items-end gap-2">@csrf @method('PATCH')<input type="hidden" name="moderation_status" value="{{ $review->moderation_status === 'visible' ? 'hidden' : 'visible' }}">@if($review->moderation_status === 'visible')<input name="moderation_reason" required placeholder="{{ __('teacher-course::reviews.reason') }}" class="min-w-0 flex-1 rounded-lg border border-slate-200 px-3 py-2 text-xs">@endif<button class="rounded-lg border px-3 py-2 text-xs font-black {{ $review->moderation_status === 'visible' ? 'border-red-200 text-red-600' : 'border-green-200 text-green-700' }}">{{ $review->moderation_status === 'visible' ? __('teacher-course::reviews.hide') : __('teacher-course::reviews.restore') }}</button></form></article>@empty<p class="py-16 text-center text-sm font-semibold text-slate-400">@lang('teacher-course::reviews.empty')</p>@endforelse</div><div class="border-t border-slate-200 p-4">{{ $reviews->links() }}</div></section></div></main>
@endsection
