@extends('Mindigo-dashboard::layouts')
@section('title', __('learning-tools::app.personalized.new') . ' · Auronsoft LMS')
@section('styles') @vite(['packages/Mindigo/Dashboard/src/resources/css/app.css', 'packages/Mindigo/Dashboard/src/resources/js/app.js']) @endsection
@section('content')
<div class="flex min-h-screen flex-col bg-slate-50">@include('learning-tools::partials.header', ['eyebrow' => __('learning-tools::app.eyebrow'), 'title' => __('learning-tools::app.personalized.new'), 'subtitle' => __('learning-tools::app.personalized.form_subtitle')])<main class="p-6"><form method="POST" action="{{ route('learning-tools.personalized.store') }}" class="mx-auto grid max-w-4xl gap-5 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:grid-cols-2">@csrf
<label class="sm:col-span-2 text-sm font-black text-slate-700">@lang('learning-tools::app.fields.title')<input name="title" value="{{ old('title') }}" required class="mt-2 h-11 w-full rounded-xl border border-slate-200 px-4 font-semibold"></label>
<label class="text-sm font-black text-slate-700">@lang('learning-tools::app.fields.subject')<select name="subject" class="mt-2 h-11 w-full rounded-xl border border-slate-200 px-4 font-semibold"><option value="">@lang('learning-tools::app.fields.all_subjects')</option>@foreach($subjects as $subject)<option @selected(old('subject', request('subject')) === $subject)>{{ $subject }}</option>@endforeach</select></label>
<label class="text-sm font-black text-slate-700">@lang('learning-tools::app.fields.topic')<input name="topic" value="{{ old('topic', request('topic')) }}" class="mt-2 h-11 w-full rounded-xl border border-slate-200 px-4 font-semibold"></label>
<label class="text-sm font-black text-slate-700">@lang('learning-tools::app.personalized.source')<select name="source" class="mt-2 h-11 w-full rounded-xl border border-slate-200 px-4 font-semibold">@foreach(['manual','weak_topics','mistakes'] as $source)<option value="{{ $source }}" @selected(old('source') === $source)>@lang('learning-tools::app.personalized.sources.' . $source)</option>@endforeach</select></label>
<label class="text-sm font-black text-slate-700">@lang('learning-tools::app.fields.difficulty')<select name="difficulty" class="mt-2 h-11 w-full rounded-xl border border-slate-200 px-4 font-semibold"><option value="">@lang('learning-tools::app.personalized.all_difficulties')</option>@foreach(['easy','medium','hard'] as $difficulty)<option value="{{ $difficulty }}" @selected(old('difficulty') === $difficulty)>@lang('learning-tools::app.difficulties.' . $difficulty)</option>@endforeach</select></label>
<label class="text-sm font-black text-slate-700">@lang('learning-tools::app.personalized.number_of_questions')<input type="number" name="question_count" min="1" max="50" value="{{ old('question_count', 10) }}" required class="mt-2 h-11 w-full rounded-xl border border-slate-200 px-4 font-semibold"></label>
@if($classrooms->isNotEmpty())<label class="text-sm font-black text-slate-700">@lang('learning-tools::app.personalized.classroom')<select name="classroom_id" class="mt-2 h-11 w-full rounded-xl border border-slate-200 px-4 font-semibold"><option value="">@lang('learning-tools::app.personalized.personal')</option>@foreach($classrooms as $classroom)<option value="{{ $classroom->id }}" @selected(old('classroom_id') == $classroom->id)>{{ $classroom->name }}</option>@endforeach</select></label>@endif
@if($errors->any())<div class="sm:col-span-2 rounded-2xl bg-red-50 p-4 text-sm font-bold text-red-700">{{ $errors->first() }}</div>@endif<div class="sm:col-span-2 flex justify-end"><button class="rounded-full bg-green-600 px-6 py-3 text-sm font-black text-white">@lang('learning-tools::app.personalized.create')</button></div></form></main></div>
@endsection
