@extends('Mindigo-dashboard::layouts')
@section('title', __('learning-tools::app.personalized.title') . ' · Mindigo LMS')
@section('styles') @vite(['packages/Mindigo/Dashboard/src/resources/css/app.css', 'packages/Mindigo/Dashboard/src/resources/js/app.js']) @endsection
@section('content')
<div class="flex min-h-screen flex-col bg-slate-50">
    @include('learning-tools::partials.header', ['eyebrow' => __('learning-tools::app.eyebrow'), 'title' => __('learning-tools::app.personalized.title'), 'subtitle' => __('learning-tools::app.personalized.subtitle'), 'actionRoute' => route('learning-tools.personalized.create'), 'actionLabel' => __('learning-tools::app.personalized.new')])
    <main class="grid gap-4 p-6 sm:grid-cols-2 xl:grid-cols-3">@forelse($sets as $set)<a href="{{ route('learning-tools.personalized.show', $set) }}" class="rounded-3xl border border-slate-200 bg-white p-5 text-slate-800 no-underline shadow-sm transition hover:border-green-200"><div class="flex justify-between"><x-heroicon-o-pencil-square class="h-8 w-8 text-green-600" /><span class="rounded-full bg-slate-100 px-3 py-1 text-[10px] font-black uppercase text-slate-600">@lang('learning-tools::app.personalized.sources.' . $set->source)</span></div><h2 class="mt-4 font-black">{{ $set->title }}</h2><p class="mt-2 text-sm font-semibold text-slate-400">{{ collect([$set->subject, $set->topic, $set->difficulty ? __('learning-tools::app.difficulties.' . $set->difficulty) : null])->filter()->join(' · ') }}</p><p class="mt-6 border-t border-slate-100 pt-4 text-xs font-black text-slate-500">{{ trans_choice('learning-tools::app.personalized.question_count', $set->questions_count, ['count' => $set->questions_count]) }} · {{ $set->classroom?->name ?? __('learning-tools::app.personalized.personal') }}</p></a>@empty<div class="col-span-full rounded-3xl border border-dashed border-slate-300 bg-white py-16 text-center"><p class="font-black text-slate-600">@lang('learning-tools::app.personalized.empty')</p></div>@endforelse<div class="col-span-full">{{ $sets->links() }}</div></main>
</div>
@endsection
