@extends('Mindigo-dashboard::layouts')
@section('title', __('Mindigo-exam-management::app.analytics.operations'))
@section('styles') @vite(['packages/Mindigo/Dashboard/src/resources/css/app.css', 'packages/Mindigo/ExamManagement/src/resources/css/app.css']) @endsection
@section('content')
<main class="exam-foundation-shell"><div class="exam-foundation-container"><x-exam::page-header :eyebrow="__('Mindigo-exam-management::app.analytics.admin_workspace')" :title="__('Mindigo-exam-management::app.analytics.operations')" :description="__('Mindigo-exam-management::app.analytics.operations_desc')" />
<section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">@foreach(['total_sessions','attempts_30_days','active_attempts','disruption_rate','events_24_hours','camera_snapshots'] as $metric)<article class="exam-foundation-stat-card"><p class="exam-stat-label">@lang('Mindigo-exam-management::app.analytics.'.$metric)</p><strong class="exam-stat-value">{{ number_format($operations[$metric], 1) }}{{ $metric === 'disruption_rate' ? '%' : '' }}</strong></article>@endforeach</section>
<x-exam::panel :title="__('Mindigo-exam-management::app.analytics.recent_sessions')"><div class="overflow-x-auto"><table class="exam-table"><thead><tr><th>@lang('Mindigo-exam-management::app.analytics.session')</th><th>@lang('Mindigo-exam-management::app.status')</th><th>@lang('Mindigo-exam-management::app.starts_at')</th><th>@lang('Mindigo-exam-management::app.ends_at')</th></tr></thead><tbody>@foreach($operations['recent_sessions'] as $session)<tr><td class="font-bold text-slate-800">{{ $session->title }}</td><td>{{ $session->status }}</td><td>{{ $session->starts_at?->format('d/m/Y H:i') ?? '—' }}</td><td>{{ $session->ends_at?->format('d/m/Y H:i') ?? '—' }}</td></tr>@endforeach</tbody></table></div></x-exam::panel>
<p class="rounded-xl border border-sky-200 bg-sky-50 p-4 text-sm font-semibold text-sky-800">@lang('Mindigo-exam-management::app.analytics.admin_privacy_note')</p></div></main>
@endsection
