@extends('Mindigo-dashboard::layouts')
@section('title', __('Mindigo-exam-management::app.analytics.title'))
@section('styles') @vite(['packages/Mindigo/Dashboard/src/resources/css/app.css', 'packages/Mindigo/ExamManagement/src/resources/css/app.css']) @endsection
@section('content')
<main class="exam-foundation-shell"><div class="exam-foundation-container">
<x-exam::page-header :eyebrow="__('Mindigo-exam-management::app.analytics.workspace')" :title="$session->title" :description="__('Mindigo-exam-management::app.analytics.description')"><x-slot:actions><x-exam::button variant="secondary" :href="route('teacher.exam-sessions.analytics.export', [$session, 'csv'])">CSV</x-exam::button><x-exam::button variant="secondary" :href="route('teacher.exam-sessions.analytics.export', [$session, 'pdf'])">PDF</x-exam::button></x-slot:actions></x-exam::page-header>
<section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach(['candidates','submitted','average_score','pass_rate'] as $metric)<article class="exam-foundation-stat-card"><p class="exam-stat-label">@lang('Mindigo-exam-management::app.analytics.'.$metric)</p><strong class="exam-stat-value">{{ number_format($summary[$metric], 1) }}{{ in_array($metric, ['average_score','pass_rate'], true) ? '%' : '' }}</strong></article>@endforeach</section>
<div class="grid gap-5 xl:grid-cols-2"><x-exam::panel :title="__('Mindigo-exam-management::app.analytics.score_distribution')"><div class="space-y-3">@foreach($distribution as $label => $count)<div class="grid grid-cols-[4rem_1fr_3rem] items-center gap-3"><span class="text-xs font-black text-slate-500">{{ $label }}</span><div class="h-3 overflow-hidden rounded-full bg-slate-100"><span class="block h-full rounded-full bg-green-600" style="width: {{ $summary['submitted'] ? max(2, $count / $summary['submitted'] * 100) : 0 }}%"></span></div><strong class="text-right text-sm text-slate-800">{{ $count }}</strong></div>@endforeach</div></x-exam::panel>
<x-exam::panel :title="__('Mindigo-exam-management::app.analytics.class_comparison')"><div class="divide-y divide-slate-100">@forelse($classrooms as $row)<div class="grid grid-cols-[1fr_auto_auto] gap-4 py-3"><strong class="text-sm text-slate-800">{{ $row['classroom']->name }}</strong><span class="text-xs font-bold text-slate-500">{{ $row['average_score'] }}%</span><span class="text-xs font-black text-green-700">{{ $row['pass_rate'] }}%</span></div>@empty<p class="py-8 text-center text-sm font-semibold text-slate-400">@lang('Mindigo-exam-management::app.analytics.no_data')</p>@endforelse</div></x-exam::panel></div>
<x-exam::panel :title="__('Mindigo-exam-management::app.analytics.question_analysis')" :description="__('Mindigo-exam-management::app.analytics.question_analysis_desc')"><div class="overflow-x-auto"><table class="exam-table"><thead><tr><th>@lang('Mindigo-exam-management::app.analytics.question')</th><th>@lang('Mindigo-exam-management::app.analytics.responses')</th><th>@lang('Mindigo-exam-management::app.analytics.correct_rate')</th><th>@lang('Mindigo-exam-management::app.analytics.blank_rate')</th><th>@lang('Mindigo-exam-management::app.analytics.average_time')</th><th>@lang('Mindigo-exam-management::app.analytics.choice_distribution')</th></tr></thead><tbody>@foreach($questions as $row)<tr><td><div class="flex items-start gap-2">@if($row['flagged'])<span title="@lang('Mindigo-exam-management::app.analytics.flagged')" class="mt-1 h-2 w-2 shrink-0 rounded-full bg-amber-500"></span>@endif<strong class="line-clamp-2 text-sm text-slate-800">{{ strip_tags($row['question']->content) }}</strong></div></td><td>{{ $row['responses'] }}</td><td class="font-black text-green-700">{{ $row['correct_rate'] }}%</td><td>{{ $row['blank_rate'] }}%</td><td>{{ __('Mindigo-exam-management::app.analytics.seconds', ['count' => $row['average_seconds']]) }}</td><td><div class="flex max-w-xs flex-wrap gap-1">@forelse($row['choice_distribution'] as $choice => $count)<span class="rounded-full bg-sky-50 px-2 py-1 text-[10px] font-bold text-sky-700">{{ $choice }}: {{ $count }}</span>@empty—@endforelse</div></td></tr>@endforeach</tbody></table></div></x-exam::panel>
<x-exam::panel :title="__('Mindigo-exam-management::app.analytics.support_students')" :description="__('Mindigo-exam-management::app.analytics.support_students_desc')"><div class="grid gap-3 md:grid-cols-2">@forelse($supportStudents as $attempt)<div class="rounded-xl border border-rose-100 bg-rose-50/50 p-4"><strong class="text-sm text-slate-900">{{ $attempt->candidate?->name ?? $attempt->user?->name }}</strong><div class="mt-2 flex justify-between text-xs font-bold text-slate-500"><span>{{ $attempt->candidate?->student_code }}</span><span class="text-rose-700">{{ $attempt->percentage }}%</span></div></div>@empty<p class="col-span-full py-8 text-center text-sm font-semibold text-slate-400">@lang('Mindigo-exam-management::app.analytics.no_support_needed')</p>@endforelse</div></x-exam::panel>
</div></main>
@endsection
