@extends('Mindigo-dashboard::layouts')
@section('title', __('teacher-live-session::app.analytics_report'))
@section('styles')
    @vite(['packages/Mindigo/Dashboard/src/resources/css/app.css', 'packages/Mindigo/Dashboard/src/resources/js/app.js'])
@endsection
@section('content')
<div class="min-h-screen bg-slate-50">
    <header class="border-b border-slate-200 bg-white px-6 py-4"><div class="flex flex-wrap items-center justify-between gap-4"><div><p class="text-xs font-black uppercase tracking-wider text-green-700">Mindigo Live</p><h1 class="mt-1 text-xl font-black text-slate-950">@lang('teacher-live-session::app.analytics_report')</h1><p class="mt-1 text-sm font-semibold text-slate-500">@lang('teacher-live-session::app.analytics_report_subtitle')</p></div><a href="{{ route('teacher.live-sessions.index') }}" class="inline-flex h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-black text-slate-700 no-underline"><x-heroicon-o-arrow-left class="h-4 w-4" />@lang('teacher-live-session::app.back_to_sessions')</a></div></header>
    <main class="space-y-5 p-4 sm:p-6">
        <form method="GET" class="grid items-end gap-3 rounded-2xl border border-slate-200 bg-white p-4 md:grid-cols-3 xl:grid-cols-7">
            <label><span class="mb-1.5 block text-xs font-black text-slate-500">@lang('teacher-live-session::app.report_scope')</span><select name="scope" class="h-10 w-full rounded-xl border border-slate-200 px-3 text-sm font-bold">@foreach(['session','classroom','course','teacher','student','provider'] as $scope)<option value="{{ $scope }}" @selected(($filters['scope'] ?? 'session') === $scope)>@lang('teacher-live-session::app.scope_'.$scope)</option>@endforeach</select></label>
            <label><span class="mb-1.5 block text-xs font-black text-slate-500">ID</span><input name="entity_id" value="{{ $filters['entity_id'] ?? '' }}" type="number" min="1" class="h-10 w-full rounded-xl border border-slate-200 px-3 text-sm"></label>
            <label><span class="mb-1.5 block text-xs font-black text-slate-500">Provider</span><select name="provider" class="h-10 w-full rounded-xl border border-slate-200 px-3 text-sm font-bold"><option value="">@lang('teacher-live-session::app.all_providers')</option>@foreach(['native','google_meet','zoom'] as $provider)<option value="{{ $provider }}" @selected(($filters['provider'] ?? '') === $provider)>{{ str($provider)->replace('_', ' ')->title() }}</option>@endforeach</select></label>
            <label><span class="mb-1.5 block text-xs font-black text-slate-500">@lang('teacher-live-session::app.date_from')</span><input name="date_from" value="{{ $filters['date_from'] ?? '' }}" type="date" class="h-10 w-full rounded-xl border border-slate-200 px-3 text-sm"></label>
            <label><span class="mb-1.5 block text-xs font-black text-slate-500">@lang('teacher-live-session::app.date_to')</span><input name="date_to" value="{{ $filters['date_to'] ?? '' }}" type="date" class="h-10 w-full rounded-xl border border-slate-200 px-3 text-sm"></label>
            <button class="h-10 rounded-xl bg-green-600 px-4 text-sm font-black text-white">@lang('teacher-live-session::app.apply_filter')</button>
            <a href="{{ route('teacher.live-sessions.reports.index') }}" class="inline-flex h-10 items-center justify-center rounded-xl border border-slate-200 text-sm font-black text-slate-600 no-underline">@lang('teacher-live-session::app.clear_filter')</a>
        </form>
        <dl class="grid overflow-hidden rounded-2xl border border-slate-200 bg-white sm:grid-cols-5">@foreach(['sessions','participants','attendance_rate','total_minutes','connection_errors'] as $metric)<div class="border-b border-slate-100 px-5 py-4 sm:border-b-0 sm:border-r"><dt class="text-[10px] font-black uppercase tracking-wider text-slate-400">@lang('teacher-live-session::app.metric_'.$metric)</dt><dd class="mt-1 text-2xl font-black text-slate-950">{{ $report['summary'][$metric] }}{{ $metric === 'attendance_rate' ? '%' : '' }}</dd></div>@endforeach</dl>
        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><h2 class="font-black text-slate-900">@lang('teacher-live-session::app.report_details')</h2><div class="flex gap-2">@foreach(['csv','xlsx','pdf'] as $format)<a href="{{ route('teacher.live-sessions.reports.export', [...$filters, 'format' => $format]) }}" class="inline-flex h-9 items-center rounded-xl {{ $format === 'csv' ? 'bg-green-600 text-white' : 'border border-slate-200 text-slate-700' }} px-3 text-xs font-black no-underline">{{ strtoupper($format) }}</a>@endforeach</div></div>
            <div class="overflow-x-auto"><table class="w-full min-w-350 text-left text-sm"><thead class="bg-slate-50 text-[10px] font-black uppercase tracking-wider text-slate-400"><tr>@foreach(['scope','sessions','participants','attendance_rate','total_minutes','late','early_leave','reconnects','microphone_minutes','camera_minutes','interaction','connection_errors'] as $column)<th class="px-4 py-3">@lang('teacher-live-session::app.column_'.$column)</th>@endforeach</tr></thead><tbody class="divide-y divide-slate-100">@forelse($report['rows'] as $row)<tr><td class="px-4 py-4 font-black text-slate-900">{{ $row['label'] }}</td><td class="px-4 py-4">{{ $row['sessions'] }}</td><td class="px-4 py-4">{{ $row['participants'] }}</td><td class="px-4 py-4 font-black text-green-700">{{ $row['attendance_rate'] }}%</td><td class="px-4 py-4">{{ $row['total_minutes'] }}</td><td class="px-4 py-4">{{ $row['late'] }}</td><td class="px-4 py-4">{{ $row['early_leave'] }}</td><td class="px-4 py-4">{{ $row['reconnects'] }}</td><td class="px-4 py-4">{{ $row['microphone_minutes'] }}</td><td class="px-4 py-4">{{ $row['camera_minutes'] }}</td><td class="px-4 py-4 text-xs">{{ $row['chat'] }} chat · {{ $row['reactions'] }} reaction · {{ $row['hands'] }} hand · {{ $row['polls'] }} poll</td><td class="px-4 py-4">{{ $row['connection_errors'] }}</td></tr>@empty<tr><td colspan="12" class="px-5 py-16 text-center text-sm font-semibold text-slate-400">@lang('teacher-live-session::app.report_empty')</td></tr>@endforelse</tbody></table></div>
        </section>
    </main>
</div>
@endsection
