<div data-mindigo-drawer="teacher-classroom-filter" class="fixed inset-0 z-40 hidden bg-slate-950/45 opacity-0 backdrop-blur-sm transition-opacity duration-200"></div>
<aside data-mindigo-drawer-panel="teacher-classroom-filter" aria-label="@lang('teacher-classroom::app.filter_title')" class="fixed inset-y-0 right-0 z-50 flex w-full max-w-md flex-col border-l border-slate-200 bg-white shadow-2xl transition-transform duration-200" style="transform: translateX(100%);">
    <header class="flex items-start justify-between gap-4 border-b border-slate-100 p-5">
        <div><p class="text-xs font-black uppercase tracking-wider text-green-700">@lang('teacher-classroom::app.filters')</p><h2 class="mt-1 text-xl font-black text-slate-950">@lang('teacher-classroom::app.filter_title')</h2><p class="mt-1 text-sm font-medium leading-6 text-slate-500">@lang('teacher-classroom::app.filter_description')</p></div>
        <button type="button" aria-label="@lang('teacher-classroom::app.close')" data-mindigo-drawer-close="teacher-classroom-filter" class="grid h-10 w-10 shrink-0 place-items-center rounded-full border border-slate-200 text-slate-500 transition hover:bg-slate-50 hover:text-slate-800"><x-heroicon-o-x-mark class="h-5 w-5" /></button>
    </header>
    <form action="{{ route('teacher.classrooms.index') }}" method="GET" class="flex flex-1 flex-col">
        <div class="flex-1 space-y-5 overflow-y-auto p-5">
            <label class="block space-y-2"><span class="block text-xs font-black uppercase tracking-wider text-slate-500">@lang('teacher-classroom::app.search_label')</span><span class="relative block"><x-heroicon-o-magnifying-glass class="pointer-events-none absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input type="search" name="keyword" value="{{ $filters['keyword'] ?? '' }}" placeholder="@lang('teacher-classroom::app.search')" class="h-11 w-full rounded-xl border border-slate-200 pl-10 pr-4 text-sm font-semibold outline-none transition focus:border-green-400 focus:ring-4 focus:ring-green-50"></span></label>
            <label class="block space-y-2"><span class="block text-xs font-black uppercase tracking-wider text-slate-500">@lang('teacher-classroom::app.status')</span><select name="status" class="h-11 w-full rounded-xl border border-slate-200 bg-white px-4 text-sm font-semibold outline-none transition focus:border-green-400 focus:ring-4 focus:ring-green-50"><option value="">@lang('teacher-classroom::app.all_status')</option><option value="active" @selected(($filters['status'] ?? '') === 'active')>@lang('teacher-classroom::app.active')</option><option value="inactive" @selected(($filters['status'] ?? '') === 'inactive')>@lang('teacher-classroom::app.inactive')</option></select></label>
        </div>
        <footer class="grid grid-cols-2 gap-3 border-t border-slate-100 p-5"><a href="{{ route('teacher.classrooms.index') }}" class="inline-flex h-11 items-center justify-center rounded-xl border border-slate-200 text-sm font-bold text-slate-600 no-underline hover:bg-slate-50">@lang('teacher-classroom::app.clear_filter')</a><button type="submit" class="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-green-600 text-sm font-bold text-white hover:bg-green-700"><x-heroicon-o-funnel class="h-4 w-4" />@lang('teacher-classroom::app.apply_filter')</button></footer>
    </form>
</aside>
